// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializeacquirePrekeyBundleRequest")
public inline fun acquirePrekeyBundleRequest(block: messenger.v1.AcquirePrekeyBundleRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.AcquirePrekeyBundleRequest =
  messenger.v1.AcquirePrekeyBundleRequestKt.Dsl._create(messenger.v1.Messenger.AcquirePrekeyBundleRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.AcquirePrekeyBundleRequest`
 */
public object AcquirePrekeyBundleRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.AcquirePrekeyBundleRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.AcquirePrekeyBundleRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.AcquirePrekeyBundleRequest = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
public inline fun messenger.v1.Messenger.AcquirePrekeyBundleRequest.copy(block: `messenger.v1`.AcquirePrekeyBundleRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.AcquirePrekeyBundleRequest =
  `messenger.v1`.AcquirePrekeyBundleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

