// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializeattachmentPreview")
public inline fun attachmentPreview(block: messenger.v1.AttachmentPreviewKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.AttachmentPreview =
  messenger.v1.AttachmentPreviewKt.Dsl._create(messenger.v1.Messenger.AttachmentPreview.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.AttachmentPreview`
 */
public object AttachmentPreviewKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.AttachmentPreview.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.AttachmentPreview.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.AttachmentPreview = _builder.build()

    /**
     * <code>int32 width = 1;</code>
     */
    public var width: kotlin.Int
      @kotlin.jvm.JvmName("getWidth")
        get() = _builder.width
      @kotlin.jvm.JvmName("setWidth")
        set(value) {
        _builder.width = value
      }
    /**
     * `int32 width = 1;`
     */
    public fun clearWidth() {
      _builder.clearWidth()
    }

    /**
     * <code>int32 height = 2;</code>
     */
    public var height: kotlin.Int
      @kotlin.jvm.JvmName("getHeight")
        get() = _builder.height
      @kotlin.jvm.JvmName("setHeight")
        set(value) {
        _builder.height = value
      }
    /**
     * `int32 height = 2;`
     */
    public fun clearHeight() {
      _builder.clearHeight()
    }
  }
}
public inline fun messenger.v1.Messenger.AttachmentPreview.copy(block: `messenger.v1`.AttachmentPreviewKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.AttachmentPreview =
  `messenger.v1`.AttachmentPreviewKt.Dsl._create(this.toBuilder()).apply { block() }._build()

