// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializeconversation")
public inline fun conversation(block: messenger.v1.ConversationKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.Conversation =
  messenger.v1.ConversationKt.Dsl._create(messenger.v1.Messenger.Conversation.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.Conversation`
 */
public object ConversationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.Conversation.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.Conversation.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.Conversation = _builder.build()

    /**
     * `string conversation_id = 1;`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 1;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `string peer_username = 2;`
     */
    public var peerUsername: kotlin.String
      @kotlin.jvm.JvmName("getPeerUsername")
        get() = _builder.peerUsername
      @kotlin.jvm.JvmName("setPeerUsername")
        set(value) {
        _builder.peerUsername = value
      }
    /**
     * `string peer_username = 2;`
     */
    public fun clearPeerUsername() {
      _builder.clearPeerUsername()
    }

    /**
     * `.messenger.v1.Profile peer_profile = 3;`
     */
    public var peerProfile: messenger.v1.Messenger.Profile
      @kotlin.jvm.JvmName("getPeerProfile")
        get() = _builder.peerProfile
      @kotlin.jvm.JvmName("setPeerProfile")
        set(value) {
        _builder.peerProfile = value
      }
    /**
     * `.messenger.v1.Profile peer_profile = 3;`
     */
    public fun clearPeerProfile() {
      _builder.clearPeerProfile()
    }
    /**
     * `.messenger.v1.Profile peer_profile = 3;`
     * @return Whether the peerProfile field is set.
     */
    public fun hasPeerProfile(): kotlin.Boolean {
      return _builder.hasPeerProfile()
    }

    public val ConversationKt.Dsl.peerProfileOrNull: messenger.v1.Messenger.Profile?
      get() = _builder.peerProfileOrNull

    /**
     * `.messenger.v1.ConversationKind kind = 4;`
     */
    public var kind: messenger.v1.Messenger.ConversationKind
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    public var kindValue: kotlin.Int
      @kotlin.jvm.JvmName("getKindValue")
        get() = _builder.kindValue
      @kotlin.jvm.JvmName("setKindValue")
        set(value) {
        _builder.kindValue = value
      }
    /**
     * `.messenger.v1.ConversationKind kind = 4;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `string title = 5;`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 5;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MemberUsernamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string member_usernames = 6;`
     * @return A list containing the memberUsernames.
     */
    public val memberUsernames: com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.memberUsernamesList
      )
    /**
     * `repeated string member_usernames = 6;`
     * @param value The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.add(value: kotlin.String) {
      _builder.addMemberUsernames(value)
    }
    /**
     * `repeated string member_usernames = 6;`
     * @param value The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMemberUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string member_usernames = 6;`
     * @param values The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMemberUsernames(values)
    }
    /**
     * `repeated string member_usernames = 6;`
     * @param values The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMemberUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string member_usernames = 6;`
     * @param index The index to set the value at.
     * @param value The memberUsernames to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMemberUsernames")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setMemberUsernames(index, value)
    }/**
     * `repeated string member_usernames = 6;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.clear() {
      _builder.clearMemberUsernames()
    }
    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MembersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     */
     public val members: com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.membersList
      )
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     * @param value The members to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMembers")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.add(value: messenger.v1.Messenger.ConversationMember) {
      _builder.addMembers(value)
    }
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     * @param value The members to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMembers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.plusAssign(value: messenger.v1.Messenger.ConversationMember) {
      add(value)
    }
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     * @param values The members to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMembers")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.addAll(values: kotlin.collections.Iterable<messenger.v1.Messenger.ConversationMember>) {
      _builder.addAllMembers(values)
    }
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     * @param values The members to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMembers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.plusAssign(values: kotlin.collections.Iterable<messenger.v1.Messenger.ConversationMember>) {
      addAll(values)
    }
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     * @param index The index to set the value at.
     * @param value The members to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMembers")
    public operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.set(index: kotlin.Int, value: messenger.v1.Messenger.ConversationMember) {
      _builder.setMembers(index, value)
    }
    /**
     * `repeated .messenger.v1.ConversationMember members = 7;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearMembers")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.ConversationMember, MembersProxy>.clear() {
      _builder.clearMembers()
    }
  }
}
public inline fun messenger.v1.Messenger.Conversation.copy(block: `messenger.v1`.ConversationKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.Conversation =
  `messenger.v1`.ConversationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val messenger.v1.Messenger.ConversationOrBuilder.peerProfileOrNull: messenger.v1.Messenger.Profile?
  get() = if (hasPeerProfile()) getPeerProfile() else null

