// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializecreateGroupConversationRequest")
public inline fun createGroupConversationRequest(block: messenger.v1.CreateGroupConversationRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.CreateGroupConversationRequest =
  messenger.v1.CreateGroupConversationRequestKt.Dsl._create(messenger.v1.Messenger.CreateGroupConversationRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.CreateGroupConversationRequest`
 */
public object CreateGroupConversationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.CreateGroupConversationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.CreateGroupConversationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.CreateGroupConversationRequest = _builder.build()

    /**
     * `string title = 1;`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 1;`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class MemberUsernamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string member_usernames = 2;`
     * @return A list containing the memberUsernames.
     */
    public val memberUsernames: com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.memberUsernamesList
      )
    /**
     * `repeated string member_usernames = 2;`
     * @param value The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.add(value: kotlin.String) {
      _builder.addMemberUsernames(value)
    }
    /**
     * `repeated string member_usernames = 2;`
     * @param value The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignMemberUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string member_usernames = 2;`
     * @param values The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMemberUsernames(values)
    }
    /**
     * `repeated string member_usernames = 2;`
     * @param values The memberUsernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllMemberUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string member_usernames = 2;`
     * @param index The index to set the value at.
     * @param value The memberUsernames to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMemberUsernames")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setMemberUsernames(index, value)
    }/**
     * `repeated string member_usernames = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setMemberUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, MemberUsernamesProxy>.clear() {
      _builder.clearMemberUsernames()
    }
    /**
     * `.messenger.v1.GroupKeyUpdate initial_key = 3;`
     */
    public var initialKey: messenger.v1.Messenger.GroupKeyUpdate
      @kotlin.jvm.JvmName("getInitialKey")
        get() = _builder.initialKey
      @kotlin.jvm.JvmName("setInitialKey")
        set(value) {
        _builder.initialKey = value
      }
    /**
     * `.messenger.v1.GroupKeyUpdate initial_key = 3;`
     */
    public fun clearInitialKey() {
      _builder.clearInitialKey()
    }
    /**
     * `.messenger.v1.GroupKeyUpdate initial_key = 3;`
     * @return Whether the initialKey field is set.
     */
    public fun hasInitialKey(): kotlin.Boolean {
      return _builder.hasInitialKey()
    }

    public val CreateGroupConversationRequestKt.Dsl.initialKeyOrNull: messenger.v1.Messenger.GroupKeyUpdate?
      get() = _builder.initialKeyOrNull
  }
}
public inline fun messenger.v1.Messenger.CreateGroupConversationRequest.copy(block: `messenger.v1`.CreateGroupConversationRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.CreateGroupConversationRequest =
  `messenger.v1`.CreateGroupConversationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val messenger.v1.Messenger.CreateGroupConversationRequestOrBuilder.initialKeyOrNull: messenger.v1.Messenger.GroupKeyUpdate?
  get() = if (hasInitialKey()) getInitialKey() else null

