// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializegetIdentityKeysRequest")
public inline fun getIdentityKeysRequest(block: messenger.v1.GetIdentityKeysRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.GetIdentityKeysRequest =
  messenger.v1.GetIdentityKeysRequestKt.Dsl._create(messenger.v1.Messenger.GetIdentityKeysRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.GetIdentityKeysRequest`
 */
public object GetIdentityKeysRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.GetIdentityKeysRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.GetIdentityKeysRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.GetIdentityKeysRequest = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsernamesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string usernames = 1;`
     * @return A list containing the usernames.
     */
    public val usernames: com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.usernamesList
      )
    /**
     * `repeated string usernames = 1;`
     * @param value The usernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.add(value: kotlin.String) {
      _builder.addUsernames(value)
    }
    /**
     * `repeated string usernames = 1;`
     * @param value The usernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string usernames = 1;`
     * @param values The usernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllUsernames(values)
    }
    /**
     * `repeated string usernames = 1;`
     * @param values The usernames to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUsernames")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string usernames = 1;`
     * @param index The index to set the value at.
     * @param value The usernames to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUsernames")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setUsernames(index, value)
    }/**
     * `repeated string usernames = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUsernames")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, UsernamesProxy>.clear() {
      _builder.clearUsernames()
    }}
}
public inline fun messenger.v1.Messenger.GetIdentityKeysRequest.copy(block: `messenger.v1`.GetIdentityKeysRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.GetIdentityKeysRequest =
  `messenger.v1`.GetIdentityKeysRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

