// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializeprepareMediaUploadRequest")
public inline fun prepareMediaUploadRequest(block: messenger.v1.PrepareMediaUploadRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.PrepareMediaUploadRequest =
  messenger.v1.PrepareMediaUploadRequestKt.Dsl._create(messenger.v1.Messenger.PrepareMediaUploadRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.PrepareMediaUploadRequest`
 */
public object PrepareMediaUploadRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.PrepareMediaUploadRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.PrepareMediaUploadRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.PrepareMediaUploadRequest = _builder.build()

    /**
     * `string filename = 1;`
     */
    public var filename: kotlin.String
      @kotlin.jvm.JvmName("getFilename")
        get() = _builder.filename
      @kotlin.jvm.JvmName("setFilename")
        set(value) {
        _builder.filename = value
      }
    /**
     * `string filename = 1;`
     */
    public fun clearFilename() {
      _builder.clearFilename()
    }

    /**
     * `string mime_type = 2;`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 2;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * <code>int64 size_bytes = 3;</code>
     */
    public var sizeBytes: kotlin.Long
      @kotlin.jvm.JvmName("getSizeBytes")
        get() = _builder.sizeBytes
      @kotlin.jvm.JvmName("setSizeBytes")
        set(value) {
        _builder.sizeBytes = value
      }
    /**
     * `int64 size_bytes = 3;`
     */
    public fun clearSizeBytes() {
      _builder.clearSizeBytes()
    }

    /**
     * `.messenger.v1.AttachmentKind kind = 4;`
     */
    public var kind: messenger.v1.Messenger.AttachmentKind
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    public var kindValue: kotlin.Int
      @kotlin.jvm.JvmName("getKindValue")
        get() = _builder.kindValue
      @kotlin.jvm.JvmName("setKindValue")
        set(value) {
        _builder.kindValue = value
      }
    /**
     * `.messenger.v1.AttachmentKind kind = 4;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }
  }
}
public inline fun messenger.v1.Messenger.PrepareMediaUploadRequest.copy(block: `messenger.v1`.PrepareMediaUploadRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.PrepareMediaUploadRequest =
  `messenger.v1`.PrepareMediaUploadRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

