// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializesearchUsersResponse")
public inline fun searchUsersResponse(block: messenger.v1.SearchUsersResponseKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.SearchUsersResponse =
  messenger.v1.SearchUsersResponseKt.Dsl._create(messenger.v1.Messenger.SearchUsersResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.SearchUsersResponse`
 */
public object SearchUsersResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.SearchUsersResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.SearchUsersResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.SearchUsersResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     */
     public val items: com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.itemsList
      )
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addItems")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.add(value: messenger.v1.Messenger.Profile) {
      _builder.addItems(value)
    }
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.plusAssign(value: messenger.v1.Messenger.Profile) {
      add(value)
    }
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllItems")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.addAll(values: kotlin.collections.Iterable<messenger.v1.Messenger.Profile>) {
      _builder.addAllItems(values)
    }
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.plusAssign(values: kotlin.collections.Iterable<messenger.v1.Messenger.Profile>) {
      addAll(values)
    }
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     * @param index The index to set the value at.
     * @param value The items to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setItems")
    public operator fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.set(index: kotlin.Int, value: messenger.v1.Messenger.Profile) {
      _builder.setItems(index, value)
    }
    /**
     * `repeated .messenger.v1.Profile items = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearItems")
    public fun com.google.protobuf.kotlin.DslList<messenger.v1.Messenger.Profile, ItemsProxy>.clear() {
      _builder.clearItems()
    }
  }
}
public inline fun messenger.v1.Messenger.SearchUsersResponse.copy(block: `messenger.v1`.SearchUsersResponseKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.SearchUsersResponse =
  `messenger.v1`.SearchUsersResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

