// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package messenger.v1;

@kotlin.jvm.JvmName("-initializestreamEventsRequest")
public inline fun streamEventsRequest(block: messenger.v1.StreamEventsRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.StreamEventsRequest =
  messenger.v1.StreamEventsRequestKt.Dsl._create(messenger.v1.Messenger.StreamEventsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.StreamEventsRequest`
 */
public object StreamEventsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: messenger.v1.Messenger.StreamEventsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: messenger.v1.Messenger.StreamEventsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): messenger.v1.Messenger.StreamEventsRequest = _builder.build()
  }
}
public inline fun messenger.v1.Messenger.StreamEventsRequest.copy(block: `messenger.v1`.StreamEventsRequestKt.Dsl.() -> kotlin.Unit): messenger.v1.Messenger.StreamEventsRequest =
  `messenger.v1`.StreamEventsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

