// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface AcquirePrekeyBundlesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.AcquirePrekeyBundlesResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .messenger.v1.PrekeyBundle items = 1;</code>
   */
  java.util.List<com.example.messenger.proto.PrekeyBundle> 
      getItemsList();
  /**
   * <code>repeated .messenger.v1.PrekeyBundle items = 1;</code>
   */
  com.example.messenger.proto.PrekeyBundle getItems(int index);
  /**
   * <code>repeated .messenger.v1.PrekeyBundle items = 1;</code>
   */
  int getItemsCount();
}
