// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeattachment")
public inline fun attachment(block: com.example.messenger.proto.AttachmentKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.Attachment =
  com.example.messenger.proto.AttachmentKt.Dsl._create(com.example.messenger.proto.Attachment.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.Attachment`
 */
public object AttachmentKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.Attachment.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.Attachment.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.Attachment = _builder.build()

    /**
     * `string attachment_id = 1;`
     */
    public var attachmentId: kotlin.String
      @kotlin.jvm.JvmName("getAttachmentId")
        get() = _builder.attachmentId
      @kotlin.jvm.JvmName("setAttachmentId")
        set(value) {
        _builder.attachmentId = value
      }
    /**
     * `string attachment_id = 1;`
     */
    public fun clearAttachmentId() {
      _builder.clearAttachmentId()
    }

    /**
     * `.messenger.v1.AttachmentKind kind = 2;`
     */
    public var kind: com.example.messenger.proto.AttachmentKind
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    public var kindValue: kotlin.Int
      @kotlin.jvm.JvmName("getKindValue")
        get() = _builder.kindValue
      @kotlin.jvm.JvmName("setKindValue")
        set(value) {
        _builder.kindValue = value
      }
    /**
     * `.messenger.v1.AttachmentKind kind = 2;`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `string filename = 3;`
     */
    public var filename: kotlin.String
      @kotlin.jvm.JvmName("getFilename")
        get() = _builder.filename
      @kotlin.jvm.JvmName("setFilename")
        set(value) {
        _builder.filename = value
      }
    /**
     * `string filename = 3;`
     */
    public fun clearFilename() {
      _builder.clearFilename()
    }

    /**
     * `string mime_type = 4;`
     */
    public var mimeType: kotlin.String
      @kotlin.jvm.JvmName("getMimeType")
        get() = _builder.mimeType
      @kotlin.jvm.JvmName("setMimeType")
        set(value) {
        _builder.mimeType = value
      }
    /**
     * `string mime_type = 4;`
     */
    public fun clearMimeType() {
      _builder.clearMimeType()
    }

    /**
     * <code>int64 size_bytes = 5;</code>
     */
    public var sizeBytes: kotlin.Long
      @kotlin.jvm.JvmName("getSizeBytes")
        get() = _builder.sizeBytes
      @kotlin.jvm.JvmName("setSizeBytes")
        set(value) {
        _builder.sizeBytes = value
      }
    /**
     * `int64 size_bytes = 5;`
     */
    public fun clearSizeBytes() {
      _builder.clearSizeBytes()
    }

    /**
     * `string media_id = 6;`
     */
    public var mediaId: kotlin.String
      @kotlin.jvm.JvmName("getMediaId")
        get() = _builder.mediaId
      @kotlin.jvm.JvmName("setMediaId")
        set(value) {
        _builder.mediaId = value
      }
    /**
     * `string media_id = 6;`
     */
    public fun clearMediaId() {
      _builder.clearMediaId()
    }

    /**
     * <code>bytes encrypted_descriptor = 7;</code>
     */
    public var encryptedDescriptor: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getEncryptedDescriptor")
        get() = _builder.encryptedDescriptor
      @kotlin.jvm.JvmName("setEncryptedDescriptor")
        set(value) {
        _builder.encryptedDescriptor = value
      }
    /**
     * `bytes encrypted_descriptor = 7;`
     */
    public fun clearEncryptedDescriptor() {
      _builder.clearEncryptedDescriptor()
    }

    /**
     * <code>bytes descriptor_nonce = 8;</code>
     */
    public var descriptorNonce: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDescriptorNonce")
        get() = _builder.descriptorNonce
      @kotlin.jvm.JvmName("setDescriptorNonce")
        set(value) {
        _builder.descriptorNonce = value
      }
    /**
     * `bytes descriptor_nonce = 8;`
     */
    public fun clearDescriptorNonce() {
      _builder.clearDescriptorNonce()
    }

    /**
     * `.messenger.v1.AttachmentPreview preview = 9;`
     */
    public var preview: com.example.messenger.proto.AttachmentPreview
      @kotlin.jvm.JvmName("getPreview")
        get() = _builder.preview
      @kotlin.jvm.JvmName("setPreview")
        set(value) {
        _builder.preview = value
      }
    /**
     * `.messenger.v1.AttachmentPreview preview = 9;`
     */
    public fun clearPreview() {
      _builder.clearPreview()
    }
    /**
     * `.messenger.v1.AttachmentPreview preview = 9;`
     * @return Whether the preview field is set.
     */
    public fun hasPreview(): kotlin.Boolean {
      return _builder.hasPreview()
    }

    public val AttachmentKt.Dsl.previewOrNull: com.example.messenger.proto.AttachmentPreview?
      get() = _builder.previewOrNull

    /**
     * <code>bytes sha256 = 10;</code>
     */
    public var sha256: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSha256")
        get() = _builder.sha256
      @kotlin.jvm.JvmName("setSha256")
        set(value) {
        _builder.sha256 = value
      }
    /**
     * `bytes sha256 = 10;`
     */
    public fun clearSha256() {
      _builder.clearSha256()
    }

    /**
     * <code>int64 ciphertext_size = 11;</code>
     */
    public var ciphertextSize: kotlin.Long
      @kotlin.jvm.JvmName("getCiphertextSize")
        get() = _builder.ciphertextSize
      @kotlin.jvm.JvmName("setCiphertextSize")
        set(value) {
        _builder.ciphertextSize = value
      }
    /**
     * `int64 ciphertext_size = 11;`
     */
    public fun clearCiphertextSize() {
      _builder.clearCiphertextSize()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class DirectEnvelopesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     */
     public val directEnvelopes: com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.directEnvelopesList
      )
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     * @param value The directEnvelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addDirectEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.add(value: com.example.messenger.proto.AttachmentDirectEnvelope) {
      _builder.addDirectEnvelopes(value)
    }
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     * @param value The directEnvelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignDirectEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.plusAssign(value: com.example.messenger.proto.AttachmentDirectEnvelope) {
      add(value)
    }
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     * @param values The directEnvelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllDirectEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.addAll(values: kotlin.collections.Iterable<com.example.messenger.proto.AttachmentDirectEnvelope>) {
      _builder.addAllDirectEnvelopes(values)
    }
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     * @param values The directEnvelopes to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllDirectEnvelopes")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.messenger.proto.AttachmentDirectEnvelope>) {
      addAll(values)
    }
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     * @param index The index to set the value at.
     * @param value The directEnvelopes to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setDirectEnvelopes")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.set(index: kotlin.Int, value: com.example.messenger.proto.AttachmentDirectEnvelope) {
      _builder.setDirectEnvelopes(index, value)
    }
    /**
     * `repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearDirectEnvelopes")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.AttachmentDirectEnvelope, DirectEnvelopesProxy>.clear() {
      _builder.clearDirectEnvelopes()
    }
  }
}
public inline fun com.example.messenger.proto.Attachment.copy(block: `com.example.messenger.proto`.AttachmentKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.Attachment =
  `com.example.messenger.proto`.AttachmentKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.messenger.proto.AttachmentOrBuilder.previewOrNull: com.example.messenger.proto.AttachmentPreview?
  get() = if (hasPreview()) getPreview() else null

