// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf enum {@code messenger.v1.AttachmentKind}
 */
public enum AttachmentKind
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>ATTACHMENT_KIND_UNSPECIFIED = 0;</code>
   */
  ATTACHMENT_KIND_UNSPECIFIED(0),
  /**
   * <code>ATTACHMENT_KIND_IMAGE = 1;</code>
   */
  ATTACHMENT_KIND_IMAGE(1),
  /**
   * <code>ATTACHMENT_KIND_VIDEO = 2;</code>
   */
  ATTACHMENT_KIND_VIDEO(2),
  /**
   * <code>ATTACHMENT_KIND_FILE = 3;</code>
   */
  ATTACHMENT_KIND_FILE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ATTACHMENT_KIND_UNSPECIFIED = 0;</code>
   */
  public static final int ATTACHMENT_KIND_UNSPECIFIED_VALUE = 0;
  /**
   * <code>ATTACHMENT_KIND_IMAGE = 1;</code>
   */
  public static final int ATTACHMENT_KIND_IMAGE_VALUE = 1;
  /**
   * <code>ATTACHMENT_KIND_VIDEO = 2;</code>
   */
  public static final int ATTACHMENT_KIND_VIDEO_VALUE = 2;
  /**
   * <code>ATTACHMENT_KIND_FILE = 3;</code>
   */
  public static final int ATTACHMENT_KIND_FILE_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AttachmentKind valueOf(int value) {
    return forNumber(value);
  }

  public static AttachmentKind forNumber(int value) {
    switch (value) {
      case 0: return ATTACHMENT_KIND_UNSPECIFIED;
      case 1: return ATTACHMENT_KIND_IMAGE;
      case 2: return ATTACHMENT_KIND_VIDEO;
      case 3: return ATTACHMENT_KIND_FILE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AttachmentKind>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AttachmentKind> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AttachmentKind>() {
          @java.lang.Override
          public AttachmentKind findValueByNumber(int number) {
            return AttachmentKind.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return AttachmentKindVerifier.INSTANCE;
  }

  private static final class AttachmentKindVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new AttachmentKindVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return AttachmentKind.forNumber(number) != null;
          }
        };

  private final int value;

  private AttachmentKind(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:messenger.v1.AttachmentKind)
}

