// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface AttachmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.Attachment)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string attachment_id = 1;</code>
   * @return The attachmentId.
   */
  java.lang.String getAttachmentId();
  /**
   * <code>string attachment_id = 1;</code>
   * @return The bytes for attachmentId.
   */
  com.google.protobuf.ByteString
      getAttachmentIdBytes();

  /**
   * <code>.messenger.v1.AttachmentKind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.messenger.v1.AttachmentKind kind = 2;</code>
   * @return The kind.
   */
  com.example.messenger.proto.AttachmentKind getKind();

  /**
   * <code>string filename = 3;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 3;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string mime_type = 4;</code>
   * @return The mimeType.
   */
  java.lang.String getMimeType();
  /**
   * <code>string mime_type = 4;</code>
   * @return The bytes for mimeType.
   */
  com.google.protobuf.ByteString
      getMimeTypeBytes();

  /**
   * <code>int64 size_bytes = 5;</code>
   * @return The sizeBytes.
   */
  long getSizeBytes();

  /**
   * <code>string media_id = 6;</code>
   * @return The mediaId.
   */
  java.lang.String getMediaId();
  /**
   * <code>string media_id = 6;</code>
   * @return The bytes for mediaId.
   */
  com.google.protobuf.ByteString
      getMediaIdBytes();

  /**
   * <code>bytes encrypted_descriptor = 7;</code>
   * @return The encryptedDescriptor.
   */
  com.google.protobuf.ByteString getEncryptedDescriptor();

  /**
   * <code>bytes descriptor_nonce = 8;</code>
   * @return The descriptorNonce.
   */
  com.google.protobuf.ByteString getDescriptorNonce();

  /**
   * <code>.messenger.v1.AttachmentPreview preview = 9;</code>
   * @return Whether the preview field is set.
   */
  boolean hasPreview();
  /**
   * <code>.messenger.v1.AttachmentPreview preview = 9;</code>
   * @return The preview.
   */
  com.example.messenger.proto.AttachmentPreview getPreview();

  /**
   * <code>bytes sha256 = 10;</code>
   * @return The sha256.
   */
  com.google.protobuf.ByteString getSha256();

  /**
   * <code>int64 ciphertext_size = 11;</code>
   * @return The ciphertextSize.
   */
  long getCiphertextSize();

  /**
   * <code>repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;</code>
   */
  java.util.List<com.example.messenger.proto.AttachmentDirectEnvelope> 
      getDirectEnvelopesList();
  /**
   * <code>repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;</code>
   */
  com.example.messenger.proto.AttachmentDirectEnvelope getDirectEnvelopes(int index);
  /**
   * <code>repeated .messenger.v1.AttachmentDirectEnvelope direct_envelopes = 12;</code>
   */
  int getDirectEnvelopesCount();
}
