// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface ConversationKeyEnvelopeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.ConversationKeyEnvelope)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>bytes encrypted_key = 2;</code>
   * @return The encryptedKey.
   */
  com.google.protobuf.ByteString getEncryptedKey();

  /**
   * <code>bytes nonce = 3;</code>
   * @return The nonce.
   */
  com.google.protobuf.ByteString getNonce();

  /**
   * <code>string sender_key_id = 4;</code>
   * @return The senderKeyId.
   */
  java.lang.String getSenderKeyId();
  /**
   * <code>string sender_key_id = 4;</code>
   * @return The bytes for senderKeyId.
   */
  com.google.protobuf.ByteString
      getSenderKeyIdBytes();

  /**
   * <code>string recipient_key_id = 5;</code>
   * @return The recipientKeyId.
   */
  java.lang.String getRecipientKeyId();
  /**
   * <code>string recipient_key_id = 5;</code>
   * @return The bytes for recipientKeyId.
   */
  com.google.protobuf.ByteString
      getRecipientKeyIdBytes();

  /**
   * <code>string device_id = 6;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 6;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
