// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeconversationMember")
public inline fun conversationMember(block: com.example.messenger.proto.ConversationMemberKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ConversationMember =
  com.example.messenger.proto.ConversationMemberKt.Dsl._create(com.example.messenger.proto.ConversationMember.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.ConversationMember`
 */
public object ConversationMemberKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.ConversationMember.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.ConversationMember.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.ConversationMember = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `.messenger.v1.ConversationRole role = 2;`
     */
    public var role: com.example.messenger.proto.ConversationRole
      @kotlin.jvm.JvmName("getRole")
        get() = _builder.role
      @kotlin.jvm.JvmName("setRole")
        set(value) {
        _builder.role = value
      }
    public var roleValue: kotlin.Int
      @kotlin.jvm.JvmName("getRoleValue")
        get() = _builder.roleValue
      @kotlin.jvm.JvmName("setRoleValue")
        set(value) {
        _builder.roleValue = value
      }
    /**
     * `.messenger.v1.ConversationRole role = 2;`
     */
    public fun clearRole() {
      _builder.clearRole()
    }

    /**
     * `string added_by = 3;`
     */
    public var addedBy: kotlin.String
      @kotlin.jvm.JvmName("getAddedBy")
        get() = _builder.addedBy
      @kotlin.jvm.JvmName("setAddedBy")
        set(value) {
        _builder.addedBy = value
      }
    /**
     * `string added_by = 3;`
     */
    public fun clearAddedBy() {
      _builder.clearAddedBy()
    }
  }
}
public inline fun com.example.messenger.proto.ConversationMember.copy(block: `com.example.messenger.proto`.ConversationMemberKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ConversationMember =
  `com.example.messenger.proto`.ConversationMemberKt.Dsl._create(this.toBuilder()).apply { block() }._build()

