// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface ConversationKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.ConversationKey)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string conversation_id = 1;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <code>string conversation_id = 1;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <code>int32 version = 2;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>string algorithm = 3;</code>
   * @return The algorithm.
   */
  java.lang.String getAlgorithm();
  /**
   * <code>string algorithm = 3;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <code>string created_by = 4;</code>
   * @return The createdBy.
   */
  java.lang.String getCreatedBy();
  /**
   * <code>string created_by = 4;</code>
   * @return The bytes for createdBy.
   */
  com.google.protobuf.ByteString
      getCreatedByBytes();

  /**
   * <code>repeated .messenger.v1.ConversationKeyEnvelope envelopes = 5;</code>
   */
  java.util.List<com.example.messenger.proto.ConversationKeyEnvelope> 
      getEnvelopesList();
  /**
   * <code>repeated .messenger.v1.ConversationKeyEnvelope envelopes = 5;</code>
   */
  com.example.messenger.proto.ConversationKeyEnvelope getEnvelopes(int index);
  /**
   * <code>repeated .messenger.v1.ConversationKeyEnvelope envelopes = 5;</code>
   */
  int getEnvelopesCount();

  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <code>.google.protobuf.Timestamp created_at = 6;</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
}
