// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.Conversation}
 */
public  final class Conversation extends
    com.google.protobuf.GeneratedMessageLite<
        Conversation, Conversation.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.Conversation)
    ConversationOrBuilder {
  private Conversation() {
    conversationId_ = "";
    peerUsername_ = "";
    title_ = "";
    memberUsernames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    members_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int CONVERSATION_ID_FIELD_NUMBER = 1;
  private java.lang.String conversationId_;
  /**
   * <code>string conversation_id = 1;</code>
   * @return The conversationId.
   */
  @java.lang.Override
  public java.lang.String getConversationId() {
    return conversationId_;
  }
  /**
   * <code>string conversation_id = 1;</code>
   * @return The bytes for conversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConversationIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(conversationId_);
  }
  /**
   * <code>string conversation_id = 1;</code>
   * @param value The conversationId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setConversationId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    conversationId_ = value;
  }
  /**
   * <code>string conversation_id = 1;</code>
   */
  private void clearConversationId() {

    conversationId_ = getDefaultInstance().getConversationId();
  }
  /**
   * <code>string conversation_id = 1;</code>
   * @param value The bytes for conversationId to set.
   */
  private void setConversationIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    conversationId_ = value.toStringUtf8();

  }

  public static final int PEER_USERNAME_FIELD_NUMBER = 2;
  private java.lang.String peerUsername_;
  /**
   * <code>string peer_username = 2;</code>
   * @return The peerUsername.
   */
  @java.lang.Override
  public java.lang.String getPeerUsername() {
    return peerUsername_;
  }
  /**
   * <code>string peer_username = 2;</code>
   * @return The bytes for peerUsername.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPeerUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(peerUsername_);
  }
  /**
   * <code>string peer_username = 2;</code>
   * @param value The peerUsername to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPeerUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    peerUsername_ = value;
  }
  /**
   * <code>string peer_username = 2;</code>
   */
  private void clearPeerUsername() {

    peerUsername_ = getDefaultInstance().getPeerUsername();
  }
  /**
   * <code>string peer_username = 2;</code>
   * @param value The bytes for peerUsername to set.
   */
  private void setPeerUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    peerUsername_ = value.toStringUtf8();

  }

  public static final int PEER_PROFILE_FIELD_NUMBER = 3;
  private com.example.messenger.proto.Profile peerProfile_;
  /**
   * <code>.messenger.v1.Profile peer_profile = 3;</code>
   */
  @java.lang.Override
  public boolean hasPeerProfile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.messenger.v1.Profile peer_profile = 3;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.Profile getPeerProfile() {
    return peerProfile_ == null ? com.example.messenger.proto.Profile.getDefaultInstance() : peerProfile_;
  }
  /**
   * <code>.messenger.v1.Profile peer_profile = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPeerProfile(com.example.messenger.proto.Profile value) {
    value.getClass();  // minimal bytecode null check
    peerProfile_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.messenger.v1.Profile peer_profile = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergePeerProfile(com.example.messenger.proto.Profile value) {
    value.getClass();  // minimal bytecode null check
    if (peerProfile_ != null &&
        peerProfile_ != com.example.messenger.proto.Profile.getDefaultInstance()) {
      peerProfile_ =
        com.example.messenger.proto.Profile.newBuilder(peerProfile_).mergeFrom(value).buildPartial();
    } else {
      peerProfile_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.messenger.v1.Profile peer_profile = 3;</code>
   */
  private void clearPeerProfile() {  peerProfile_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private int kind_;
  /**
   * <code>.messenger.v1.ConversationKind kind = 4;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.messenger.v1.ConversationKind kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public com.example.messenger.proto.ConversationKind getKind() {
    com.example.messenger.proto.ConversationKind result = com.example.messenger.proto.ConversationKind.forNumber(kind_);
    return result == null ? com.example.messenger.proto.ConversationKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.messenger.v1.ConversationKind kind = 4;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.messenger.v1.ConversationKind kind = 4;</code>
   * @param value The kind to set.
   */
  private void setKind(com.example.messenger.proto.ConversationKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.messenger.v1.ConversationKind kind = 4;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static final int TITLE_FIELD_NUMBER = 5;
  private java.lang.String title_;
  /**
   * <code>string title = 5;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <code>string title = 5;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <code>string title = 5;</code>
   * @param value The title to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTitle(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    title_ = value;
  }
  /**
   * <code>string title = 5;</code>
   */
  private void clearTitle() {

    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <code>string title = 5;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();

  }

  public static final int MEMBER_USERNAMES_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> memberUsernames_;
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @return A list containing the memberUsernames.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getMemberUsernamesList() {
    return memberUsernames_;
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @return The count of memberUsernames.
   */
  @java.lang.Override
  public int getMemberUsernamesCount() {
    return memberUsernames_.size();
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param index The index of the element to return.
   * @return The memberUsernames at the given index.
   */
  @java.lang.Override
  public java.lang.String getMemberUsernames(int index) {
    return memberUsernames_.get(index);
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the memberUsernames at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMemberUsernamesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        memberUsernames_.get(index));
  }
  private void ensureMemberUsernamesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        memberUsernames_;  if (!tmp.isModifiable()) {
      memberUsernames_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param index The index to set the value at.
   * @param value The memberUsernames to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMemberUsernames(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureMemberUsernamesIsMutable();
    memberUsernames_.set(index, value);
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param value The memberUsernames to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addMemberUsernames(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureMemberUsernamesIsMutable();
    memberUsernames_.add(value);
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param values The memberUsernames to add.
   */
  private void addAllMemberUsernames(
      java.lang.Iterable<java.lang.String> values) {
    ensureMemberUsernamesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, memberUsernames_);
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   */
  private void clearMemberUsernames() {
    memberUsernames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string member_usernames = 6;</code>
   * @param value The bytes of the memberUsernames to add.
   */
  private void addMemberUsernamesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureMemberUsernamesIsMutable();
    memberUsernames_.add(value.toStringUtf8());
  }

  public static final int MEMBERS_FIELD_NUMBER = 7;
  private com.google.protobuf.Internal.ProtobufList<com.example.messenger.proto.ConversationMember> members_;
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.messenger.proto.ConversationMember> getMembersList() {
    return members_;
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  public java.util.List<? extends com.example.messenger.proto.ConversationMemberOrBuilder> 
      getMembersOrBuilderList() {
    return members_;
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.Override
  public int getMembersCount() {
    return members_.size();
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.ConversationMember getMembers(int index) {
    return members_.get(index);
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  public com.example.messenger.proto.ConversationMemberOrBuilder getMembersOrBuilder(
      int index) {
    return members_.get(index);
  }
  private void ensureMembersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.example.messenger.proto.ConversationMember> tmp = members_;
    if (!tmp.isModifiable()) {
      members_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMembers(
      int index, com.example.messenger.proto.ConversationMember value) {
    value.getClass();  // minimal bytecode null check
    ensureMembersIsMutable();
    members_.set(index, value);
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addMembers(com.example.messenger.proto.ConversationMember value) {
    value.getClass();  // minimal bytecode null check
    ensureMembersIsMutable();
    members_.add(value);
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addMembers(
      int index, com.example.messenger.proto.ConversationMember value) {
    value.getClass();  // minimal bytecode null check
    ensureMembersIsMutable();
    members_.add(index, value);
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  private void addAllMembers(
      java.lang.Iterable<? extends com.example.messenger.proto.ConversationMember> values) {
    ensureMembersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, members_);
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  private void clearMembers() {
    members_ = emptyProtobufList();
  }
  /**
   * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
   */
  private void removeMembers(int index) {
    ensureMembersIsMutable();
    members_.remove(index);
  }

  public static com.example.messenger.proto.Conversation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.Conversation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.Conversation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.Conversation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.Conversation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.Conversation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.Conversation prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.Conversation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.Conversation, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.Conversation)
      com.example.messenger.proto.ConversationOrBuilder {
    // Construct using com.example.messenger.proto.Conversation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string conversation_id = 1;</code>
     * @return The conversationId.
     */
    @java.lang.Override
    public java.lang.String getConversationId() {
      return instance.getConversationId();
    }
    /**
     * <code>string conversation_id = 1;</code>
     * @return The bytes for conversationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConversationIdBytes() {
      return instance.getConversationIdBytes();
    }
    /**
     * <code>string conversation_id = 1;</code>
     * @param value The conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationId(
        java.lang.String value) {
      copyOnWrite();
      instance.setConversationId(value);
      return this;
    }
    /**
     * <code>string conversation_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearConversationId() {
      copyOnWrite();
      instance.clearConversationId();
      return this;
    }
    /**
     * <code>string conversation_id = 1;</code>
     * @param value The bytes for conversationId to set.
     * @return This builder for chaining.
     */
    public Builder setConversationIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setConversationIdBytes(value);
      return this;
    }

    /**
     * <code>string peer_username = 2;</code>
     * @return The peerUsername.
     */
    @java.lang.Override
    public java.lang.String getPeerUsername() {
      return instance.getPeerUsername();
    }
    /**
     * <code>string peer_username = 2;</code>
     * @return The bytes for peerUsername.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPeerUsernameBytes() {
      return instance.getPeerUsernameBytes();
    }
    /**
     * <code>string peer_username = 2;</code>
     * @param value The peerUsername to set.
     * @return This builder for chaining.
     */
    public Builder setPeerUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setPeerUsername(value);
      return this;
    }
    /**
     * <code>string peer_username = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeerUsername() {
      copyOnWrite();
      instance.clearPeerUsername();
      return this;
    }
    /**
     * <code>string peer_username = 2;</code>
     * @param value The bytes for peerUsername to set.
     * @return This builder for chaining.
     */
    public Builder setPeerUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPeerUsernameBytes(value);
      return this;
    }

    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    @java.lang.Override
    public boolean hasPeerProfile() {
      return instance.hasPeerProfile();
    }
    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.Profile getPeerProfile() {
      return instance.getPeerProfile();
    }
    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    public Builder setPeerProfile(com.example.messenger.proto.Profile value) {
      copyOnWrite();
      instance.setPeerProfile(value);
      return this;
      }
    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    public Builder setPeerProfile(
        com.example.messenger.proto.Profile.Builder builderForValue) {
      copyOnWrite();
      instance.setPeerProfile(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    public Builder mergePeerProfile(com.example.messenger.proto.Profile value) {
      copyOnWrite();
      instance.mergePeerProfile(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Profile peer_profile = 3;</code>
     */
    public Builder clearPeerProfile() {  copyOnWrite();
      instance.clearPeerProfile();
      return this;
    }

    /**
     * <code>.messenger.v1.ConversationKind kind = 4;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.messenger.v1.ConversationKind kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ConversationKind kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.example.messenger.proto.ConversationKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.messenger.v1.ConversationKind kind = 4;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.example.messenger.proto.ConversationKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ConversationKind kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    /**
     * <code>string title = 5;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <code>string title = 5;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <code>string title = 5;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <code>string title = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <code>string title = 5;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <code>repeated string member_usernames = 6;</code>
     * @return A list containing the memberUsernames.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getMemberUsernamesList() {
      return java.util.Collections.unmodifiableList(
          instance.getMemberUsernamesList());
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @return The count of memberUsernames.
     */
    @java.lang.Override
    public int getMemberUsernamesCount() {
      return instance.getMemberUsernamesCount();
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param index The index of the element to return.
     * @return The memberUsernames at the given index.
     */
    @java.lang.Override
    public java.lang.String getMemberUsernames(int index) {
      return instance.getMemberUsernames(index);
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the memberUsernames at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMemberUsernamesBytes(int index) {
      return instance.getMemberUsernamesBytes(index);
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param index The index to set the value at.
     * @param value The memberUsernames to set.
     * @return This builder for chaining.
     */
    public Builder setMemberUsernames(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setMemberUsernames(index, value);
      return this;
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param value The memberUsernames to add.
     * @return This builder for chaining.
     */
    public Builder addMemberUsernames(
        java.lang.String value) {
      copyOnWrite();
      instance.addMemberUsernames(value);
      return this;
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param values The memberUsernames to add.
     * @return This builder for chaining.
     */
    public Builder addAllMemberUsernames(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllMemberUsernames(values);
      return this;
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemberUsernames() {
      copyOnWrite();
      instance.clearMemberUsernames();
      return this;
    }
    /**
     * <code>repeated string member_usernames = 6;</code>
     * @param value The bytes of the memberUsernames to add.
     * @return This builder for chaining.
     */
    public Builder addMemberUsernamesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addMemberUsernamesBytes(value);
      return this;
    }

    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    @java.lang.Override
    public java.util.List<com.example.messenger.proto.ConversationMember> getMembersList() {
      return java.util.Collections.unmodifiableList(
          instance.getMembersList());
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    @java.lang.Override
    public int getMembersCount() {
      return instance.getMembersCount();
    }/**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.ConversationMember getMembers(int index) {
      return instance.getMembers(index);
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder setMembers(
        int index, com.example.messenger.proto.ConversationMember value) {
      copyOnWrite();
      instance.setMembers(index, value);
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder setMembers(
        int index, com.example.messenger.proto.ConversationMember.Builder builderForValue) {
      copyOnWrite();
      instance.setMembers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder addMembers(com.example.messenger.proto.ConversationMember value) {
      copyOnWrite();
      instance.addMembers(value);
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder addMembers(
        int index, com.example.messenger.proto.ConversationMember value) {
      copyOnWrite();
      instance.addMembers(index, value);
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder addMembers(
        com.example.messenger.proto.ConversationMember.Builder builderForValue) {
      copyOnWrite();
      instance.addMembers(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder addMembers(
        int index, com.example.messenger.proto.ConversationMember.Builder builderForValue) {
      copyOnWrite();
      instance.addMembers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder addAllMembers(
        java.lang.Iterable<? extends com.example.messenger.proto.ConversationMember> values) {
      copyOnWrite();
      instance.addAllMembers(values);
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder clearMembers() {
      copyOnWrite();
      instance.clearMembers();
      return this;
    }
    /**
     * <code>repeated .messenger.v1.ConversationMember members = 7;</code>
     */
    public Builder removeMembers(int index) {
      copyOnWrite();
      instance.removeMembers(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.Conversation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.Conversation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "conversationId_",
            "peerUsername_",
            "peerProfile_",
            "kind_",
            "title_",
            "memberUsernames_",
            "members_",
            com.example.messenger.proto.ConversationMember.class,
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0002\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u1009\u0000\u0004\f\u0005\u0208\u0006\u021a\u0007\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.Conversation> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.Conversation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.Conversation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.Conversation)
  private static final com.example.messenger.proto.Conversation DEFAULT_INSTANCE;
  static {
    Conversation defaultInstance = new Conversation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Conversation.class, defaultInstance);
  }

  public static com.example.messenger.proto.Conversation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Conversation> PARSER;

  public static com.google.protobuf.Parser<Conversation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

