// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.ConversationKeyEnvelope}
 */
public  final class ConversationKeyEnvelope extends
    com.google.protobuf.GeneratedMessageLite<
        ConversationKeyEnvelope, ConversationKeyEnvelope.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.ConversationKeyEnvelope)
    ConversationKeyEnvelopeOrBuilder {
  private ConversationKeyEnvelope() {
    username_ = "";
    encryptedKey_ = com.google.protobuf.ByteString.EMPTY;
    nonce_ = com.google.protobuf.ByteString.EMPTY;
    senderKeyId_ = "";
    recipientKeyId_ = "";
    deviceId_ = "";
  }
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();

  }

  public static final int ENCRYPTED_KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString encryptedKey_;
  /**
   * <code>bytes encrypted_key = 2;</code>
   * @return The encryptedKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedKey() {
    return encryptedKey_;
  }
  /**
   * <code>bytes encrypted_key = 2;</code>
   * @param value The encryptedKey to set.
   */
  private void setEncryptedKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    encryptedKey_ = value;
  }
  /**
   * <code>bytes encrypted_key = 2;</code>
   */
  private void clearEncryptedKey() {

    encryptedKey_ = getDefaultInstance().getEncryptedKey();
  }

  public static final int NONCE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString nonce_;
  /**
   * <code>bytes nonce = 3;</code>
   * @return The nonce.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getNonce() {
    return nonce_;
  }
  /**
   * <code>bytes nonce = 3;</code>
   * @param value The nonce to set.
   */
  private void setNonce(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    nonce_ = value;
  }
  /**
   * <code>bytes nonce = 3;</code>
   */
  private void clearNonce() {

    nonce_ = getDefaultInstance().getNonce();
  }

  public static final int SENDER_KEY_ID_FIELD_NUMBER = 4;
  private java.lang.String senderKeyId_;
  /**
   * <code>string sender_key_id = 4;</code>
   * @return The senderKeyId.
   */
  @java.lang.Override
  public java.lang.String getSenderKeyId() {
    return senderKeyId_;
  }
  /**
   * <code>string sender_key_id = 4;</code>
   * @return The bytes for senderKeyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderKeyIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(senderKeyId_);
  }
  /**
   * <code>string sender_key_id = 4;</code>
   * @param value The senderKeyId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSenderKeyId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    senderKeyId_ = value;
  }
  /**
   * <code>string sender_key_id = 4;</code>
   */
  private void clearSenderKeyId() {

    senderKeyId_ = getDefaultInstance().getSenderKeyId();
  }
  /**
   * <code>string sender_key_id = 4;</code>
   * @param value The bytes for senderKeyId to set.
   */
  private void setSenderKeyIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    senderKeyId_ = value.toStringUtf8();

  }

  public static final int RECIPIENT_KEY_ID_FIELD_NUMBER = 5;
  private java.lang.String recipientKeyId_;
  /**
   * <code>string recipient_key_id = 5;</code>
   * @return The recipientKeyId.
   */
  @java.lang.Override
  public java.lang.String getRecipientKeyId() {
    return recipientKeyId_;
  }
  /**
   * <code>string recipient_key_id = 5;</code>
   * @return The bytes for recipientKeyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientKeyIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(recipientKeyId_);
  }
  /**
   * <code>string recipient_key_id = 5;</code>
   * @param value The recipientKeyId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setRecipientKeyId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    recipientKeyId_ = value;
  }
  /**
   * <code>string recipient_key_id = 5;</code>
   */
  private void clearRecipientKeyId() {

    recipientKeyId_ = getDefaultInstance().getRecipientKeyId();
  }
  /**
   * <code>string recipient_key_id = 5;</code>
   * @param value The bytes for recipientKeyId to set.
   */
  private void setRecipientKeyIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    recipientKeyId_ = value.toStringUtf8();

  }

  public static final int DEVICE_ID_FIELD_NUMBER = 6;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 6;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 6;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 6;</code>
   * @param value The deviceId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDeviceId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    deviceId_ = value;
  }
  /**
   * <code>string device_id = 6;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 6;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.ConversationKeyEnvelope parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.ConversationKeyEnvelope parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ConversationKeyEnvelope parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.ConversationKeyEnvelope prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.ConversationKeyEnvelope}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.ConversationKeyEnvelope, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.ConversationKeyEnvelope)
      com.example.messenger.proto.ConversationKeyEnvelopeOrBuilder {
    // Construct using com.example.messenger.proto.ConversationKeyEnvelope.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>bytes encrypted_key = 2;</code>
     * @return The encryptedKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedKey() {
      return instance.getEncryptedKey();
    }
    /**
     * <code>bytes encrypted_key = 2;</code>
     * @param value The encryptedKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncryptedKey(value);
      return this;
    }
    /**
     * <code>bytes encrypted_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedKey() {
      copyOnWrite();
      instance.clearEncryptedKey();
      return this;
    }

    /**
     * <code>bytes nonce = 3;</code>
     * @return The nonce.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getNonce() {
      return instance.getNonce();
    }
    /**
     * <code>bytes nonce = 3;</code>
     * @param value The nonce to set.
     * @return This builder for chaining.
     */
    public Builder setNonce(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNonce(value);
      return this;
    }
    /**
     * <code>bytes nonce = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonce() {
      copyOnWrite();
      instance.clearNonce();
      return this;
    }

    /**
     * <code>string sender_key_id = 4;</code>
     * @return The senderKeyId.
     */
    @java.lang.Override
    public java.lang.String getSenderKeyId() {
      return instance.getSenderKeyId();
    }
    /**
     * <code>string sender_key_id = 4;</code>
     * @return The bytes for senderKeyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSenderKeyIdBytes() {
      return instance.getSenderKeyIdBytes();
    }
    /**
     * <code>string sender_key_id = 4;</code>
     * @param value The senderKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderKeyId(
        java.lang.String value) {
      copyOnWrite();
      instance.setSenderKeyId(value);
      return this;
    }
    /**
     * <code>string sender_key_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderKeyId() {
      copyOnWrite();
      instance.clearSenderKeyId();
      return this;
    }
    /**
     * <code>string sender_key_id = 4;</code>
     * @param value The bytes for senderKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderKeyIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSenderKeyIdBytes(value);
      return this;
    }

    /**
     * <code>string recipient_key_id = 5;</code>
     * @return The recipientKeyId.
     */
    @java.lang.Override
    public java.lang.String getRecipientKeyId() {
      return instance.getRecipientKeyId();
    }
    /**
     * <code>string recipient_key_id = 5;</code>
     * @return The bytes for recipientKeyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecipientKeyIdBytes() {
      return instance.getRecipientKeyIdBytes();
    }
    /**
     * <code>string recipient_key_id = 5;</code>
     * @param value The recipientKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientKeyId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRecipientKeyId(value);
      return this;
    }
    /**
     * <code>string recipient_key_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipientKeyId() {
      copyOnWrite();
      instance.clearRecipientKeyId();
      return this;
    }
    /**
     * <code>string recipient_key_id = 5;</code>
     * @param value The bytes for recipientKeyId to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientKeyIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRecipientKeyIdBytes(value);
      return this;
    }

    /**
     * <code>string device_id = 6;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 6;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 6;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 6;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.ConversationKeyEnvelope)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.ConversationKeyEnvelope();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "username_",
            "encryptedKey_",
            "nonce_",
            "senderKeyId_",
            "recipientKeyId_",
            "deviceId_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\n" +
              "\u0003\n\u0004\u0208\u0005\u0208\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.ConversationKeyEnvelope> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.ConversationKeyEnvelope.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.ConversationKeyEnvelope>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.ConversationKeyEnvelope)
  private static final com.example.messenger.proto.ConversationKeyEnvelope DEFAULT_INSTANCE;
  static {
    ConversationKeyEnvelope defaultInstance = new ConversationKeyEnvelope();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ConversationKeyEnvelope.class, defaultInstance);
  }

  public static com.example.messenger.proto.ConversationKeyEnvelope getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ConversationKeyEnvelope> PARSER;

  public static com.google.protobuf.Parser<ConversationKeyEnvelope> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

