// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.GetArchivePublicKeysRequest}
 */
public  final class GetArchivePublicKeysRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetArchivePublicKeysRequest, GetArchivePublicKeysRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.GetArchivePublicKeysRequest)
    GetArchivePublicKeysRequestOrBuilder {
  private GetArchivePublicKeysRequest() {
    usernames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int USERNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> usernames_;
  /**
   * <code>repeated string usernames = 1;</code>
   * @return A list containing the usernames.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getUsernamesList() {
    return usernames_;
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @return The count of usernames.
   */
  @java.lang.Override
  public int getUsernamesCount() {
    return usernames_.size();
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the element to return.
   * @return The usernames at the given index.
   */
  @java.lang.Override
  public java.lang.String getUsernames(int index) {
    return usernames_.get(index);
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the usernames at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernamesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        usernames_.get(index));
  }
  private void ensureUsernamesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        usernames_;  if (!tmp.isModifiable()) {
      usernames_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index to set the value at.
   * @param value The usernames to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsernames(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureUsernamesIsMutable();
    usernames_.set(index, value);
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param value The usernames to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addUsernames(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureUsernamesIsMutable();
    usernames_.add(value);
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param values The usernames to add.
   */
  private void addAllUsernames(
      java.lang.Iterable<java.lang.String> values) {
    ensureUsernamesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, usernames_);
  }
  /**
   * <code>repeated string usernames = 1;</code>
   */
  private void clearUsernames() {
    usernames_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string usernames = 1;</code>
   * @param value The bytes of the usernames to add.
   */
  private void addUsernamesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureUsernamesIsMutable();
    usernames_.add(value.toStringUtf8());
  }

  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.GetArchivePublicKeysRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.GetArchivePublicKeysRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.GetArchivePublicKeysRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.GetArchivePublicKeysRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.GetArchivePublicKeysRequest)
      com.example.messenger.proto.GetArchivePublicKeysRequestOrBuilder {
    // Construct using com.example.messenger.proto.GetArchivePublicKeysRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string usernames = 1;</code>
     * @return A list containing the usernames.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getUsernamesList() {
      return java.util.Collections.unmodifiableList(
          instance.getUsernamesList());
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @return The count of usernames.
     */
    @java.lang.Override
    public int getUsernamesCount() {
      return instance.getUsernamesCount();
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index of the element to return.
     * @return The usernames at the given index.
     */
    @java.lang.Override
    public java.lang.String getUsernames(int index) {
      return instance.getUsernames(index);
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the usernames at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernamesBytes(int index) {
      return instance.getUsernamesBytes(index);
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param index The index to set the value at.
     * @param value The usernames to set.
     * @return This builder for chaining.
     */
    public Builder setUsernames(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setUsernames(index, value);
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param value The usernames to add.
     * @return This builder for chaining.
     */
    public Builder addUsernames(
        java.lang.String value) {
      copyOnWrite();
      instance.addUsernames(value);
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param values The usernames to add.
     * @return This builder for chaining.
     */
    public Builder addAllUsernames(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllUsernames(values);
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsernames() {
      copyOnWrite();
      instance.clearUsernames();
      return this;
    }
    /**
     * <code>repeated string usernames = 1;</code>
     * @param value The bytes of the usernames to add.
     * @return This builder for chaining.
     */
    public Builder addUsernamesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addUsernamesBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.GetArchivePublicKeysRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.GetArchivePublicKeysRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "usernames_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.GetArchivePublicKeysRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.GetArchivePublicKeysRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.GetArchivePublicKeysRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.GetArchivePublicKeysRequest)
  private static final com.example.messenger.proto.GetArchivePublicKeysRequest DEFAULT_INSTANCE;
  static {
    GetArchivePublicKeysRequest defaultInstance = new GetArchivePublicKeysRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetArchivePublicKeysRequest.class, defaultInstance);
  }

  public static com.example.messenger.proto.GetArchivePublicKeysRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetArchivePublicKeysRequest> PARSER;

  public static com.google.protobuf.Parser<GetArchivePublicKeysRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

