// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializegetArchivePublicKeysResponse")
public inline fun getArchivePublicKeysResponse(block: com.example.messenger.proto.GetArchivePublicKeysResponseKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.GetArchivePublicKeysResponse =
  com.example.messenger.proto.GetArchivePublicKeysResponseKt.Dsl._create(com.example.messenger.proto.GetArchivePublicKeysResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.GetArchivePublicKeysResponse`
 */
public object GetArchivePublicKeysResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.GetArchivePublicKeysResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.GetArchivePublicKeysResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.GetArchivePublicKeysResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ItemsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     */
     public val items: com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.itemsList
      )
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addItems")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.add(value: com.example.messenger.proto.ArchiveKeyBundle) {
      _builder.addItems(value)
    }
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     * @param value The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.plusAssign(value: com.example.messenger.proto.ArchiveKeyBundle) {
      add(value)
    }
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllItems")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.addAll(values: kotlin.collections.Iterable<com.example.messenger.proto.ArchiveKeyBundle>) {
      _builder.addAllItems(values)
    }
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     * @param values The items to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllItems")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.messenger.proto.ArchiveKeyBundle>) {
      addAll(values)
    }
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     * @param index The index to set the value at.
     * @param value The items to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setItems")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.set(index: kotlin.Int, value: com.example.messenger.proto.ArchiveKeyBundle) {
      _builder.setItems(index, value)
    }
    /**
     * `repeated .messenger.v1.ArchiveKeyBundle items = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearItems")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.ArchiveKeyBundle, ItemsProxy>.clear() {
      _builder.clearItems()
    }
  }
}
public inline fun com.example.messenger.proto.GetArchivePublicKeysResponse.copy(block: `com.example.messenger.proto`.GetArchivePublicKeysResponseKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.GetArchivePublicKeysResponse =
  `com.example.messenger.proto`.GetArchivePublicKeysResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

