// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializegetConversationKeyRequest")
public inline fun getConversationKeyRequest(block: com.example.messenger.proto.GetConversationKeyRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.GetConversationKeyRequest =
  com.example.messenger.proto.GetConversationKeyRequestKt.Dsl._create(com.example.messenger.proto.GetConversationKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.GetConversationKeyRequest`
 */
public object GetConversationKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.GetConversationKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.GetConversationKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.GetConversationKeyRequest = _builder.build()

    /**
     * `string conversation_id = 1;`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 1;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * <code>int32 version = 2;</code>
     */
    public var version: kotlin.Int
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int32 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
public inline fun com.example.messenger.proto.GetConversationKeyRequest.copy(block: `com.example.messenger.proto`.GetConversationKeyRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.GetConversationKeyRequest =
  `com.example.messenger.proto`.GetConversationKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

