// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface GetIdentityKeysRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.GetIdentityKeysRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated string usernames = 1;</code>
   * @return A list containing the usernames.
   */
  java.util.List<java.lang.String>
      getUsernamesList();
  /**
   * <code>repeated string usernames = 1;</code>
   * @return The count of usernames.
   */
  int getUsernamesCount();
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the element to return.
   * @return The usernames at the given index.
   */
  java.lang.String getUsernames(int index);
  /**
   * <code>repeated string usernames = 1;</code>
   * @param index The index of the element to return.
   * @return The usernames at the given index.
   */
  com.google.protobuf.ByteString
      getUsernamesBytes(int index);
}
