// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializehistoryArchiveRecord")
public inline fun historyArchiveRecord(block: com.example.messenger.proto.HistoryArchiveRecordKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.HistoryArchiveRecord =
  com.example.messenger.proto.HistoryArchiveRecordKt.Dsl._create(com.example.messenger.proto.HistoryArchiveRecord.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.HistoryArchiveRecord`
 */
public object HistoryArchiveRecordKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.HistoryArchiveRecord.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.HistoryArchiveRecord.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.HistoryArchiveRecord = _builder.build()

    /**
     * <code>int64 sequence = 1;</code>
     */
    public var sequence: kotlin.Long
      @kotlin.jvm.JvmName("getSequence")
        get() = _builder.sequence
      @kotlin.jvm.JvmName("setSequence")
        set(value) {
        _builder.sequence = value
      }
    /**
     * `int64 sequence = 1;`
     */
    public fun clearSequence() {
      _builder.clearSequence()
    }

    /**
     * `string record_id = 2;`
     */
    public var recordId: kotlin.String
      @kotlin.jvm.JvmName("getRecordId")
        get() = _builder.recordId
      @kotlin.jvm.JvmName("setRecordId")
        set(value) {
        _builder.recordId = value
      }
    /**
     * `string record_id = 2;`
     */
    public fun clearRecordId() {
      _builder.clearRecordId()
    }

    /**
     * `string owner_username = 3;`
     */
    public var ownerUsername: kotlin.String
      @kotlin.jvm.JvmName("getOwnerUsername")
        get() = _builder.ownerUsername
      @kotlin.jvm.JvmName("setOwnerUsername")
        set(value) {
        _builder.ownerUsername = value
      }
    /**
     * `string owner_username = 3;`
     */
    public fun clearOwnerUsername() {
      _builder.clearOwnerUsername()
    }

    /**
     * `string conversation_id = 4;`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 4;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `.messenger.v1.HistoryArchiveRecordType record_type = 5;`
     */
    public var recordType: com.example.messenger.proto.HistoryArchiveRecordType
      @kotlin.jvm.JvmName("getRecordType")
        get() = _builder.recordType
      @kotlin.jvm.JvmName("setRecordType")
        set(value) {
        _builder.recordType = value
      }
    public var recordTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getRecordTypeValue")
        get() = _builder.recordTypeValue
      @kotlin.jvm.JvmName("setRecordTypeValue")
        set(value) {
        _builder.recordTypeValue = value
      }
    /**
     * `.messenger.v1.HistoryArchiveRecordType record_type = 5;`
     */
    public fun clearRecordType() {
      _builder.clearRecordType()
    }

    /**
     * <code>int64 message_id = 6;</code>
     */
    public var messageId: kotlin.Long
      @kotlin.jvm.JvmName("getMessageId")
        get() = _builder.messageId
      @kotlin.jvm.JvmName("setMessageId")
        set(value) {
        _builder.messageId = value
      }
    /**
     * `int64 message_id = 6;`
     */
    public fun clearMessageId() {
      _builder.clearMessageId()
    }

    /**
     * `string attachment_id = 7;`
     */
    public var attachmentId: kotlin.String
      @kotlin.jvm.JvmName("getAttachmentId")
        get() = _builder.attachmentId
      @kotlin.jvm.JvmName("setAttachmentId")
        set(value) {
        _builder.attachmentId = value
      }
    /**
     * `string attachment_id = 7;`
     */
    public fun clearAttachmentId() {
      _builder.clearAttachmentId()
    }

    /**
     * <code>int32 group_key_version = 8;</code>
     */
    public var groupKeyVersion: kotlin.Int
      @kotlin.jvm.JvmName("getGroupKeyVersion")
        get() = _builder.groupKeyVersion
      @kotlin.jvm.JvmName("setGroupKeyVersion")
        set(value) {
        _builder.groupKeyVersion = value
      }
    /**
     * `int32 group_key_version = 8;`
     */
    public fun clearGroupKeyVersion() {
      _builder.clearGroupKeyVersion()
    }

    /**
     * `string sender = 9;`
     */
    public var sender: kotlin.String
      @kotlin.jvm.JvmName("getSender")
        get() = _builder.sender
      @kotlin.jvm.JvmName("setSender")
        set(value) {
        _builder.sender = value
      }
    /**
     * `string sender = 9;`
     */
    public fun clearSender() {
      _builder.clearSender()
    }

    /**
     * `.google.protobuf.Timestamp created_at = 10;`
     */
    public var createdAt: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `.google.protobuf.Timestamp created_at = 10;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
    /**
     * `.google.protobuf.Timestamp created_at = 10;`
     * @return Whether the createdAt field is set.
     */
    public fun hasCreatedAt(): kotlin.Boolean {
      return _builder.hasCreatedAt()
    }

    public val HistoryArchiveRecordKt.Dsl.createdAtOrNull: com.google.protobuf.Timestamp?
      get() = _builder.createdAtOrNull

    /**
     * <code>bytes ciphertext = 11;</code>
     */
    public var ciphertext: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getCiphertext")
        get() = _builder.ciphertext
      @kotlin.jvm.JvmName("setCiphertext")
        set(value) {
        _builder.ciphertext = value
      }
    /**
     * `bytes ciphertext = 11;`
     */
    public fun clearCiphertext() {
      _builder.clearCiphertext()
    }

    /**
     * <code>bytes nonce = 12;</code>
     */
    public var nonce: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getNonce")
        get() = _builder.nonce
      @kotlin.jvm.JvmName("setNonce")
        set(value) {
        _builder.nonce = value
      }
    /**
     * `bytes nonce = 12;`
     */
    public fun clearNonce() {
      _builder.clearNonce()
    }

    /**
     * <code>bytes ephemeral_public_key = 13;</code>
     */
    public var ephemeralPublicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getEphemeralPublicKey")
        get() = _builder.ephemeralPublicKey
      @kotlin.jvm.JvmName("setEphemeralPublicKey")
        set(value) {
        _builder.ephemeralPublicKey = value
      }
    /**
     * `bytes ephemeral_public_key = 13;`
     */
    public fun clearEphemeralPublicKey() {
      _builder.clearEphemeralPublicKey()
    }

    /**
     * <code>int32 archive_key_version = 14;</code>
     */
    public var archiveKeyVersion: kotlin.Int
      @kotlin.jvm.JvmName("getArchiveKeyVersion")
        get() = _builder.archiveKeyVersion
      @kotlin.jvm.JvmName("setArchiveKeyVersion")
        set(value) {
        _builder.archiveKeyVersion = value
      }
    /**
     * `int32 archive_key_version = 14;`
     */
    public fun clearArchiveKeyVersion() {
      _builder.clearArchiveKeyVersion()
    }
  }
}
public inline fun com.example.messenger.proto.HistoryArchiveRecord.copy(block: `com.example.messenger.proto`.HistoryArchiveRecordKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.HistoryArchiveRecord =
  `com.example.messenger.proto`.HistoryArchiveRecordKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.messenger.proto.HistoryArchiveRecordOrBuilder.createdAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasCreatedAt()) getCreatedAt() else null

