// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.HistoryArchiveHeader}
 */
public  final class HistoryArchiveHeader extends
    com.google.protobuf.GeneratedMessageLite<
        HistoryArchiveHeader, HistoryArchiveHeader.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.HistoryArchiveHeader)
    HistoryArchiveHeaderOrBuilder {
  private HistoryArchiveHeader() {
    username_ = "";
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    encryptedPrivateKey_ = com.google.protobuf.ByteString.EMPTY;
    kdfSalt_ = com.google.protobuf.ByteString.EMPTY;
    kdfParams_ = "";
  }
  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();

  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>bytes public_key = 2;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }
  /**
   * <code>bytes public_key = 2;</code>
   * @param value The publicKey to set.
   */
  private void setPublicKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    publicKey_ = value;
  }
  /**
   * <code>bytes public_key = 2;</code>
   */
  private void clearPublicKey() {

    publicKey_ = getDefaultInstance().getPublicKey();
  }

  public static final int ENCRYPTED_PRIVATE_KEY_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString encryptedPrivateKey_;
  /**
   * <code>bytes encrypted_private_key = 3;</code>
   * @return The encryptedPrivateKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedPrivateKey() {
    return encryptedPrivateKey_;
  }
  /**
   * <code>bytes encrypted_private_key = 3;</code>
   * @param value The encryptedPrivateKey to set.
   */
  private void setEncryptedPrivateKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    encryptedPrivateKey_ = value;
  }
  /**
   * <code>bytes encrypted_private_key = 3;</code>
   */
  private void clearEncryptedPrivateKey() {

    encryptedPrivateKey_ = getDefaultInstance().getEncryptedPrivateKey();
  }

  public static final int KDF_SALT_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString kdfSalt_;
  /**
   * <code>bytes kdf_salt = 4;</code>
   * @return The kdfSalt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKdfSalt() {
    return kdfSalt_;
  }
  /**
   * <code>bytes kdf_salt = 4;</code>
   * @param value The kdfSalt to set.
   */
  private void setKdfSalt(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    kdfSalt_ = value;
  }
  /**
   * <code>bytes kdf_salt = 4;</code>
   */
  private void clearKdfSalt() {

    kdfSalt_ = getDefaultInstance().getKdfSalt();
  }

  public static final int KDF_PARAMS_FIELD_NUMBER = 5;
  private java.lang.String kdfParams_;
  /**
   * <code>string kdf_params = 5;</code>
   * @return The kdfParams.
   */
  @java.lang.Override
  public java.lang.String getKdfParams() {
    return kdfParams_;
  }
  /**
   * <code>string kdf_params = 5;</code>
   * @return The bytes for kdfParams.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKdfParamsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(kdfParams_);
  }
  /**
   * <code>string kdf_params = 5;</code>
   * @param value The kdfParams to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKdfParams(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    kdfParams_ = value;
  }
  /**
   * <code>string kdf_params = 5;</code>
   */
  private void clearKdfParams() {

    kdfParams_ = getDefaultInstance().getKdfParams();
  }
  /**
   * <code>string kdf_params = 5;</code>
   * @param value The bytes for kdfParams to set.
   */
  private void setKdfParamsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    kdfParams_ = value.toStringUtf8();

  }

  public static final int VERSION_FIELD_NUMBER = 6;
  private int version_;
  /**
   * <code>int32 version = 6;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }
  /**
   * <code>int32 version = 6;</code>
   * @param value The version to set.
   */
  private void setVersion(int value) {
    
    version_ = value;
  }
  /**
   * <code>int32 version = 6;</code>
   */
  private void clearVersion() {

    version_ = 0;
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 7;
  private com.google.protobuf.Timestamp updatedAt_;
  /**
   * <code>.google.protobuf.Timestamp updated_at = 7;</code>
   */
  @java.lang.Override
  public boolean hasUpdatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 7;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getUpdatedAt() {
    return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUpdatedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    updatedAt_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeUpdatedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    if (updatedAt_ != null &&
        updatedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      updatedAt_ =
        com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
    } else {
      updatedAt_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.Timestamp updated_at = 7;</code>
   */
  private void clearUpdatedAt() {  updatedAt_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.HistoryArchiveHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.HistoryArchiveHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.HistoryArchiveHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.HistoryArchiveHeader prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.HistoryArchiveHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.HistoryArchiveHeader, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.HistoryArchiveHeader)
      com.example.messenger.proto.HistoryArchiveHeaderOrBuilder {
    // Construct using com.example.messenger.proto.HistoryArchiveHeader.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>bytes public_key = 2;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return instance.getPublicKey();
    }
    /**
     * <code>bytes public_key = 2;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKey(value);
      return this;
    }
    /**
     * <code>bytes public_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      copyOnWrite();
      instance.clearPublicKey();
      return this;
    }

    /**
     * <code>bytes encrypted_private_key = 3;</code>
     * @return The encryptedPrivateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedPrivateKey() {
      return instance.getEncryptedPrivateKey();
    }
    /**
     * <code>bytes encrypted_private_key = 3;</code>
     * @param value The encryptedPrivateKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedPrivateKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncryptedPrivateKey(value);
      return this;
    }
    /**
     * <code>bytes encrypted_private_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedPrivateKey() {
      copyOnWrite();
      instance.clearEncryptedPrivateKey();
      return this;
    }

    /**
     * <code>bytes kdf_salt = 4;</code>
     * @return The kdfSalt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKdfSalt() {
      return instance.getKdfSalt();
    }
    /**
     * <code>bytes kdf_salt = 4;</code>
     * @param value The kdfSalt to set.
     * @return This builder for chaining.
     */
    public Builder setKdfSalt(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKdfSalt(value);
      return this;
    }
    /**
     * <code>bytes kdf_salt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKdfSalt() {
      copyOnWrite();
      instance.clearKdfSalt();
      return this;
    }

    /**
     * <code>string kdf_params = 5;</code>
     * @return The kdfParams.
     */
    @java.lang.Override
    public java.lang.String getKdfParams() {
      return instance.getKdfParams();
    }
    /**
     * <code>string kdf_params = 5;</code>
     * @return The bytes for kdfParams.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKdfParamsBytes() {
      return instance.getKdfParamsBytes();
    }
    /**
     * <code>string kdf_params = 5;</code>
     * @param value The kdfParams to set.
     * @return This builder for chaining.
     */
    public Builder setKdfParams(
        java.lang.String value) {
      copyOnWrite();
      instance.setKdfParams(value);
      return this;
    }
    /**
     * <code>string kdf_params = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearKdfParams() {
      copyOnWrite();
      instance.clearKdfParams();
      return this;
    }
    /**
     * <code>string kdf_params = 5;</code>
     * @param value The bytes for kdfParams to set.
     * @return This builder for chaining.
     */
    public Builder setKdfParamsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKdfParamsBytes(value);
      return this;
    }

    /**
     * <code>int32 version = 6;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>int32 version = 6;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>int32 version = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    @java.lang.Override
    public boolean hasUpdatedAt() {
      return instance.hasUpdatedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return instance.getUpdatedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setUpdatedAt(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public Builder setUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setUpdatedAt(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeUpdatedAt(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 7;</code>
     */
    public Builder clearUpdatedAt() {  copyOnWrite();
      instance.clearUpdatedAt();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.HistoryArchiveHeader)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.HistoryArchiveHeader();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "username_",
            "publicKey_",
            "encryptedPrivateKey_",
            "kdfSalt_",
            "kdfParams_",
            "version_",
            "updatedAt_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\n" +
              "\u0003\n\u0004\n\u0005\u0208\u0006\u0004\u0007\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.HistoryArchiveHeader> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.HistoryArchiveHeader.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.HistoryArchiveHeader>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.HistoryArchiveHeader)
  private static final com.example.messenger.proto.HistoryArchiveHeader DEFAULT_INSTANCE;
  static {
    HistoryArchiveHeader defaultInstance = new HistoryArchiveHeader();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      HistoryArchiveHeader.class, defaultInstance);
  }

  public static com.example.messenger.proto.HistoryArchiveHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<HistoryArchiveHeader> PARSER;

  public static com.google.protobuf.Parser<HistoryArchiveHeader> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

