// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.IdentityKey}
 */
public  final class IdentityKey extends
    com.google.protobuf.GeneratedMessageLite<
        IdentityKey, IdentityKey.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.IdentityKey)
    IdentityKeyOrBuilder {
  private IdentityKey() {
    username_ = "";
    keyId_ = "";
    algorithm_ = "";
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    deviceId_ = "";
  }
  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();

  }

  public static final int KEY_ID_FIELD_NUMBER = 2;
  private java.lang.String keyId_;
  /**
   * <code>string key_id = 2;</code>
   * @return The keyId.
   */
  @java.lang.Override
  public java.lang.String getKeyId() {
    return keyId_;
  }
  /**
   * <code>string key_id = 2;</code>
   * @return The bytes for keyId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(keyId_);
  }
  /**
   * <code>string key_id = 2;</code>
   * @param value The keyId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKeyId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    keyId_ = value;
  }
  /**
   * <code>string key_id = 2;</code>
   */
  private void clearKeyId() {

    keyId_ = getDefaultInstance().getKeyId();
  }
  /**
   * <code>string key_id = 2;</code>
   * @param value The bytes for keyId to set.
   */
  private void setKeyIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    keyId_ = value.toStringUtf8();

  }

  public static final int ALGORITHM_FIELD_NUMBER = 3;
  private java.lang.String algorithm_;
  /**
   * <code>string algorithm = 3;</code>
   * @return The algorithm.
   */
  @java.lang.Override
  public java.lang.String getAlgorithm() {
    return algorithm_;
  }
  /**
   * <code>string algorithm = 3;</code>
   * @return The bytes for algorithm.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlgorithmBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(algorithm_);
  }
  /**
   * <code>string algorithm = 3;</code>
   * @param value The algorithm to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAlgorithm(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    algorithm_ = value;
  }
  /**
   * <code>string algorithm = 3;</code>
   */
  private void clearAlgorithm() {

    algorithm_ = getDefaultInstance().getAlgorithm();
  }
  /**
   * <code>string algorithm = 3;</code>
   * @param value The bytes for algorithm to set.
   */
  private void setAlgorithmBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    algorithm_ = value.toStringUtf8();

  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>bytes public_key = 4;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }
  /**
   * <code>bytes public_key = 4;</code>
   * @param value The publicKey to set.
   */
  private void setPublicKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    publicKey_ = value;
  }
  /**
   * <code>bytes public_key = 4;</code>
   */
  private void clearPublicKey() {

    publicKey_ = getDefaultInstance().getPublicKey();
  }

  public static final int PUBLISHED_AT_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp publishedAt_;
  /**
   * <code>.google.protobuf.Timestamp published_at = 5;</code>
   */
  @java.lang.Override
  public boolean hasPublishedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp published_at = 5;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getPublishedAt() {
    return publishedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : publishedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp published_at = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPublishedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    publishedAt_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.google.protobuf.Timestamp published_at = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergePublishedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    if (publishedAt_ != null &&
        publishedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      publishedAt_ =
        com.google.protobuf.Timestamp.newBuilder(publishedAt_).mergeFrom(value).buildPartial();
    } else {
      publishedAt_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.Timestamp published_at = 5;</code>
   */
  private void clearPublishedAt() {  publishedAt_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 6;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 6;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 6;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 6;</code>
   * @param value The deviceId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDeviceId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    deviceId_ = value;
  }
  /**
   * <code>string device_id = 6;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 6;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static com.example.messenger.proto.IdentityKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.IdentityKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.IdentityKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.IdentityKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.IdentityKey prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.IdentityKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.IdentityKey, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.IdentityKey)
      com.example.messenger.proto.IdentityKeyOrBuilder {
    // Construct using com.example.messenger.proto.IdentityKey.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>string key_id = 2;</code>
     * @return The keyId.
     */
    @java.lang.Override
    public java.lang.String getKeyId() {
      return instance.getKeyId();
    }
    /**
     * <code>string key_id = 2;</code>
     * @return The bytes for keyId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyIdBytes() {
      return instance.getKeyIdBytes();
    }
    /**
     * <code>string key_id = 2;</code>
     * @param value The keyId to set.
     * @return This builder for chaining.
     */
    public Builder setKeyId(
        java.lang.String value) {
      copyOnWrite();
      instance.setKeyId(value);
      return this;
    }
    /**
     * <code>string key_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyId() {
      copyOnWrite();
      instance.clearKeyId();
      return this;
    }
    /**
     * <code>string key_id = 2;</code>
     * @param value The bytes for keyId to set.
     * @return This builder for chaining.
     */
    public Builder setKeyIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKeyIdBytes(value);
      return this;
    }

    /**
     * <code>string algorithm = 3;</code>
     * @return The algorithm.
     */
    @java.lang.Override
    public java.lang.String getAlgorithm() {
      return instance.getAlgorithm();
    }
    /**
     * <code>string algorithm = 3;</code>
     * @return The bytes for algorithm.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlgorithmBytes() {
      return instance.getAlgorithmBytes();
    }
    /**
     * <code>string algorithm = 3;</code>
     * @param value The algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithm(
        java.lang.String value) {
      copyOnWrite();
      instance.setAlgorithm(value);
      return this;
    }
    /**
     * <code>string algorithm = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlgorithm() {
      copyOnWrite();
      instance.clearAlgorithm();
      return this;
    }
    /**
     * <code>string algorithm = 3;</code>
     * @param value The bytes for algorithm to set.
     * @return This builder for chaining.
     */
    public Builder setAlgorithmBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAlgorithmBytes(value);
      return this;
    }

    /**
     * <code>bytes public_key = 4;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return instance.getPublicKey();
    }
    /**
     * <code>bytes public_key = 4;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKey(value);
      return this;
    }
    /**
     * <code>bytes public_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      copyOnWrite();
      instance.clearPublicKey();
      return this;
    }

    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    @java.lang.Override
    public boolean hasPublishedAt() {
      return instance.hasPublishedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getPublishedAt() {
      return instance.getPublishedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    public Builder setPublishedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setPublishedAt(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    public Builder setPublishedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setPublishedAt(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    public Builder mergePublishedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergePublishedAt(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp published_at = 5;</code>
     */
    public Builder clearPublishedAt() {  copyOnWrite();
      instance.clearPublishedAt();
      return this;
    }

    /**
     * <code>string device_id = 6;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 6;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 6;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 6;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.IdentityKey)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.IdentityKey();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "username_",
            "keyId_",
            "algorithm_",
            "publicKey_",
            "publishedAt_",
            "deviceId_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0001\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\n\u0005\u1009\u0000\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.IdentityKey> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.IdentityKey.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.IdentityKey>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.IdentityKey)
  private static final com.example.messenger.proto.IdentityKey DEFAULT_INSTANCE;
  static {
    IdentityKey defaultInstance = new IdentityKey();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      IdentityKey.class, defaultInstance);
  }

  public static com.example.messenger.proto.IdentityKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<IdentityKey> PARSER;

  public static com.google.protobuf.Parser<IdentityKey> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

