// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeinitializeHistoryArchiveRequest")
public inline fun initializeHistoryArchiveRequest(block: com.example.messenger.proto.InitializeHistoryArchiveRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.InitializeHistoryArchiveRequest =
  com.example.messenger.proto.InitializeHistoryArchiveRequestKt.Dsl._create(com.example.messenger.proto.InitializeHistoryArchiveRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.InitializeHistoryArchiveRequest`
 */
public object InitializeHistoryArchiveRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.InitializeHistoryArchiveRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.InitializeHistoryArchiveRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.InitializeHistoryArchiveRequest = _builder.build()

    /**
     * <code>bytes public_key = 1;</code>
     */
    public var publicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPublicKey")
        get() = _builder.publicKey
      @kotlin.jvm.JvmName("setPublicKey")
        set(value) {
        _builder.publicKey = value
      }
    /**
     * `bytes public_key = 1;`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }

    /**
     * <code>bytes encrypted_private_key = 2;</code>
     */
    public var encryptedPrivateKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getEncryptedPrivateKey")
        get() = _builder.encryptedPrivateKey
      @kotlin.jvm.JvmName("setEncryptedPrivateKey")
        set(value) {
        _builder.encryptedPrivateKey = value
      }
    /**
     * `bytes encrypted_private_key = 2;`
     */
    public fun clearEncryptedPrivateKey() {
      _builder.clearEncryptedPrivateKey()
    }

    /**
     * <code>bytes kdf_salt = 3;</code>
     */
    public var kdfSalt: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getKdfSalt")
        get() = _builder.kdfSalt
      @kotlin.jvm.JvmName("setKdfSalt")
        set(value) {
        _builder.kdfSalt = value
      }
    /**
     * `bytes kdf_salt = 3;`
     */
    public fun clearKdfSalt() {
      _builder.clearKdfSalt()
    }

    /**
     * `string kdf_params = 4;`
     */
    public var kdfParams: kotlin.String
      @kotlin.jvm.JvmName("getKdfParams")
        get() = _builder.kdfParams
      @kotlin.jvm.JvmName("setKdfParams")
        set(value) {
        _builder.kdfParams = value
      }
    /**
     * `string kdf_params = 4;`
     */
    public fun clearKdfParams() {
      _builder.clearKdfParams()
    }

    /**
     * <code>int32 version = 5;</code>
     */
    public var version: kotlin.Int
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int32 version = 5;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
public inline fun com.example.messenger.proto.InitializeHistoryArchiveRequest.copy(block: `com.example.messenger.proto`.InitializeHistoryArchiveRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.InitializeHistoryArchiveRequest =
  `com.example.messenger.proto`.InitializeHistoryArchiveRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

