// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.InitializeHistoryArchiveRequest}
 */
public  final class InitializeHistoryArchiveRequest extends
    com.google.protobuf.GeneratedMessageLite<
        InitializeHistoryArchiveRequest, InitializeHistoryArchiveRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.InitializeHistoryArchiveRequest)
    InitializeHistoryArchiveRequestOrBuilder {
  private InitializeHistoryArchiveRequest() {
    publicKey_ = com.google.protobuf.ByteString.EMPTY;
    encryptedPrivateKey_ = com.google.protobuf.ByteString.EMPTY;
    kdfSalt_ = com.google.protobuf.ByteString.EMPTY;
    kdfParams_ = "";
  }
  public static final int PUBLIC_KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString publicKey_;
  /**
   * <code>bytes public_key = 1;</code>
   * @return The publicKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPublicKey() {
    return publicKey_;
  }
  /**
   * <code>bytes public_key = 1;</code>
   * @param value The publicKey to set.
   */
  private void setPublicKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    publicKey_ = value;
  }
  /**
   * <code>bytes public_key = 1;</code>
   */
  private void clearPublicKey() {

    publicKey_ = getDefaultInstance().getPublicKey();
  }

  public static final int ENCRYPTED_PRIVATE_KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString encryptedPrivateKey_;
  /**
   * <code>bytes encrypted_private_key = 2;</code>
   * @return The encryptedPrivateKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedPrivateKey() {
    return encryptedPrivateKey_;
  }
  /**
   * <code>bytes encrypted_private_key = 2;</code>
   * @param value The encryptedPrivateKey to set.
   */
  private void setEncryptedPrivateKey(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    encryptedPrivateKey_ = value;
  }
  /**
   * <code>bytes encrypted_private_key = 2;</code>
   */
  private void clearEncryptedPrivateKey() {

    encryptedPrivateKey_ = getDefaultInstance().getEncryptedPrivateKey();
  }

  public static final int KDF_SALT_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString kdfSalt_;
  /**
   * <code>bytes kdf_salt = 3;</code>
   * @return The kdfSalt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKdfSalt() {
    return kdfSalt_;
  }
  /**
   * <code>bytes kdf_salt = 3;</code>
   * @param value The kdfSalt to set.
   */
  private void setKdfSalt(com.google.protobuf.ByteString value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    kdfSalt_ = value;
  }
  /**
   * <code>bytes kdf_salt = 3;</code>
   */
  private void clearKdfSalt() {

    kdfSalt_ = getDefaultInstance().getKdfSalt();
  }

  public static final int KDF_PARAMS_FIELD_NUMBER = 4;
  private java.lang.String kdfParams_;
  /**
   * <code>string kdf_params = 4;</code>
   * @return The kdfParams.
   */
  @java.lang.Override
  public java.lang.String getKdfParams() {
    return kdfParams_;
  }
  /**
   * <code>string kdf_params = 4;</code>
   * @return The bytes for kdfParams.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKdfParamsBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(kdfParams_);
  }
  /**
   * <code>string kdf_params = 4;</code>
   * @param value The kdfParams to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKdfParams(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    kdfParams_ = value;
  }
  /**
   * <code>string kdf_params = 4;</code>
   */
  private void clearKdfParams() {

    kdfParams_ = getDefaultInstance().getKdfParams();
  }
  /**
   * <code>string kdf_params = 4;</code>
   * @param value The bytes for kdfParams to set.
   */
  private void setKdfParamsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    kdfParams_ = value.toStringUtf8();

  }

  public static final int VERSION_FIELD_NUMBER = 5;
  private int version_;
  /**
   * <code>int32 version = 5;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }
  /**
   * <code>int32 version = 5;</code>
   * @param value The version to set.
   */
  private void setVersion(int value) {
    
    version_ = value;
  }
  /**
   * <code>int32 version = 5;</code>
   */
  private void clearVersion() {

    version_ = 0;
  }

  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.InitializeHistoryArchiveRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.InitializeHistoryArchiveRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.InitializeHistoryArchiveRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.InitializeHistoryArchiveRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.InitializeHistoryArchiveRequest)
      com.example.messenger.proto.InitializeHistoryArchiveRequestOrBuilder {
    // Construct using com.example.messenger.proto.InitializeHistoryArchiveRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bytes public_key = 1;</code>
     * @return The publicKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPublicKey() {
      return instance.getPublicKey();
    }
    /**
     * <code>bytes public_key = 1;</code>
     * @param value The publicKey to set.
     * @return This builder for chaining.
     */
    public Builder setPublicKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPublicKey(value);
      return this;
    }
    /**
     * <code>bytes public_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicKey() {
      copyOnWrite();
      instance.clearPublicKey();
      return this;
    }

    /**
     * <code>bytes encrypted_private_key = 2;</code>
     * @return The encryptedPrivateKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedPrivateKey() {
      return instance.getEncryptedPrivateKey();
    }
    /**
     * <code>bytes encrypted_private_key = 2;</code>
     * @param value The encryptedPrivateKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedPrivateKey(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEncryptedPrivateKey(value);
      return this;
    }
    /**
     * <code>bytes encrypted_private_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedPrivateKey() {
      copyOnWrite();
      instance.clearEncryptedPrivateKey();
      return this;
    }

    /**
     * <code>bytes kdf_salt = 3;</code>
     * @return The kdfSalt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKdfSalt() {
      return instance.getKdfSalt();
    }
    /**
     * <code>bytes kdf_salt = 3;</code>
     * @param value The kdfSalt to set.
     * @return This builder for chaining.
     */
    public Builder setKdfSalt(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKdfSalt(value);
      return this;
    }
    /**
     * <code>bytes kdf_salt = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKdfSalt() {
      copyOnWrite();
      instance.clearKdfSalt();
      return this;
    }

    /**
     * <code>string kdf_params = 4;</code>
     * @return The kdfParams.
     */
    @java.lang.Override
    public java.lang.String getKdfParams() {
      return instance.getKdfParams();
    }
    /**
     * <code>string kdf_params = 4;</code>
     * @return The bytes for kdfParams.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKdfParamsBytes() {
      return instance.getKdfParamsBytes();
    }
    /**
     * <code>string kdf_params = 4;</code>
     * @param value The kdfParams to set.
     * @return This builder for chaining.
     */
    public Builder setKdfParams(
        java.lang.String value) {
      copyOnWrite();
      instance.setKdfParams(value);
      return this;
    }
    /**
     * <code>string kdf_params = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKdfParams() {
      copyOnWrite();
      instance.clearKdfParams();
      return this;
    }
    /**
     * <code>string kdf_params = 4;</code>
     * @param value The bytes for kdfParams to set.
     * @return This builder for chaining.
     */
    public Builder setKdfParamsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setKdfParamsBytes(value);
      return this;
    }

    /**
     * <code>int32 version = 5;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>int32 version = 5;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>int32 version = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.InitializeHistoryArchiveRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.InitializeHistoryArchiveRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "publicKey_",
            "encryptedPrivateKey_",
            "kdfSalt_",
            "kdfParams_",
            "version_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
              "\n\u0004\u0208\u0005\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.InitializeHistoryArchiveRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.InitializeHistoryArchiveRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.InitializeHistoryArchiveRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.InitializeHistoryArchiveRequest)
  private static final com.example.messenger.proto.InitializeHistoryArchiveRequest DEFAULT_INSTANCE;
  static {
    InitializeHistoryArchiveRequest defaultInstance = new InitializeHistoryArchiveRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      InitializeHistoryArchiveRequest.class, defaultInstance);
  }

  public static com.example.messenger.proto.InitializeHistoryArchiveRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<InitializeHistoryArchiveRequest> PARSER;

  public static com.google.protobuf.Parser<InitializeHistoryArchiveRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

