// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeleaveGroupConversationRequest")
public inline fun leaveGroupConversationRequest(block: com.example.messenger.proto.LeaveGroupConversationRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.LeaveGroupConversationRequest =
  com.example.messenger.proto.LeaveGroupConversationRequestKt.Dsl._create(com.example.messenger.proto.LeaveGroupConversationRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.LeaveGroupConversationRequest`
 */
public object LeaveGroupConversationRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.LeaveGroupConversationRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.LeaveGroupConversationRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.LeaveGroupConversationRequest = _builder.build()

    /**
     * `string conversation_id = 1;`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 1;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `.messenger.v1.GroupKeyUpdate next_key = 2;`
     */
    public var nextKey: com.example.messenger.proto.GroupKeyUpdate
      @kotlin.jvm.JvmName("getNextKey")
        get() = _builder.nextKey
      @kotlin.jvm.JvmName("setNextKey")
        set(value) {
        _builder.nextKey = value
      }
    /**
     * `.messenger.v1.GroupKeyUpdate next_key = 2;`
     */
    public fun clearNextKey() {
      _builder.clearNextKey()
    }
    /**
     * `.messenger.v1.GroupKeyUpdate next_key = 2;`
     * @return Whether the nextKey field is set.
     */
    public fun hasNextKey(): kotlin.Boolean {
      return _builder.hasNextKey()
    }

    public val LeaveGroupConversationRequestKt.Dsl.nextKeyOrNull: com.example.messenger.proto.GroupKeyUpdate?
      get() = _builder.nextKeyOrNull
  }
}
public inline fun com.example.messenger.proto.LeaveGroupConversationRequest.copy(block: `com.example.messenger.proto`.LeaveGroupConversationRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.LeaveGroupConversationRequest =
  `com.example.messenger.proto`.LeaveGroupConversationRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.messenger.proto.LeaveGroupConversationRequestOrBuilder.nextKeyOrNull: com.example.messenger.proto.GroupKeyUpdate?
  get() = if (hasNextKey()) getNextKey() else null

