// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializelistHistoryArchiveRecordsRequest")
public inline fun listHistoryArchiveRecordsRequest(block: com.example.messenger.proto.ListHistoryArchiveRecordsRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ListHistoryArchiveRecordsRequest =
  com.example.messenger.proto.ListHistoryArchiveRecordsRequestKt.Dsl._create(com.example.messenger.proto.ListHistoryArchiveRecordsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.ListHistoryArchiveRecordsRequest`
 */
public object ListHistoryArchiveRecordsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.ListHistoryArchiveRecordsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.ListHistoryArchiveRecordsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.ListHistoryArchiveRecordsRequest = _builder.build()

    /**
     * <code>int64 after_sequence = 1;</code>
     */
    public var afterSequence: kotlin.Long
      @kotlin.jvm.JvmName("getAfterSequence")
        get() = _builder.afterSequence
      @kotlin.jvm.JvmName("setAfterSequence")
        set(value) {
        _builder.afterSequence = value
      }
    /**
     * `int64 after_sequence = 1;`
     */
    public fun clearAfterSequence() {
      _builder.clearAfterSequence()
    }

    /**
     * <code>int32 limit = 2;</code>
     */
    public var limit: kotlin.Int
      @kotlin.jvm.JvmName("getLimit")
        get() = _builder.limit
      @kotlin.jvm.JvmName("setLimit")
        set(value) {
        _builder.limit = value
      }
    /**
     * `int32 limit = 2;`
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }
  }
}
public inline fun com.example.messenger.proto.ListHistoryArchiveRecordsRequest.copy(block: `com.example.messenger.proto`.ListHistoryArchiveRecordsRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ListHistoryArchiveRecordsRequest =
  `com.example.messenger.proto`.ListHistoryArchiveRecordsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

