// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.ListHistoryArchiveRecordsRequest}
 */
public  final class ListHistoryArchiveRecordsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ListHistoryArchiveRecordsRequest, ListHistoryArchiveRecordsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.ListHistoryArchiveRecordsRequest)
    ListHistoryArchiveRecordsRequestOrBuilder {
  private ListHistoryArchiveRecordsRequest() {
  }
  public static final int AFTER_SEQUENCE_FIELD_NUMBER = 1;
  private long afterSequence_;
  /**
   * <code>int64 after_sequence = 1;</code>
   * @return The afterSequence.
   */
  @java.lang.Override
  public long getAfterSequence() {
    return afterSequence_;
  }
  /**
   * <code>int64 after_sequence = 1;</code>
   * @param value The afterSequence to set.
   */
  private void setAfterSequence(long value) {
    
    afterSequence_ = value;
  }
  /**
   * <code>int64 after_sequence = 1;</code>
   */
  private void clearAfterSequence() {

    afterSequence_ = 0L;
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_;
  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }
  /**
   * <code>int32 limit = 2;</code>
   * @param value The limit to set.
   */
  private void setLimit(int value) {
    
    limit_ = value;
  }
  /**
   * <code>int32 limit = 2;</code>
   */
  private void clearLimit() {

    limit_ = 0;
  }

  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.ListHistoryArchiveRecordsRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.ListHistoryArchiveRecordsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.ListHistoryArchiveRecordsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.ListHistoryArchiveRecordsRequest)
      com.example.messenger.proto.ListHistoryArchiveRecordsRequestOrBuilder {
    // Construct using com.example.messenger.proto.ListHistoryArchiveRecordsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 after_sequence = 1;</code>
     * @return The afterSequence.
     */
    @java.lang.Override
    public long getAfterSequence() {
      return instance.getAfterSequence();
    }
    /**
     * <code>int64 after_sequence = 1;</code>
     * @param value The afterSequence to set.
     * @return This builder for chaining.
     */
    public Builder setAfterSequence(long value) {
      copyOnWrite();
      instance.setAfterSequence(value);
      return this;
    }
    /**
     * <code>int64 after_sequence = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAfterSequence() {
      copyOnWrite();
      instance.clearAfterSequence();
      return this;
    }

    /**
     * <code>int32 limit = 2;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <code>int32 limit = 2;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <code>int32 limit = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.ListHistoryArchiveRecordsRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.ListHistoryArchiveRecordsRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "afterSequence_",
            "limit_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0002\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.ListHistoryArchiveRecordsRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.ListHistoryArchiveRecordsRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.ListHistoryArchiveRecordsRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.ListHistoryArchiveRecordsRequest)
  private static final com.example.messenger.proto.ListHistoryArchiveRecordsRequest DEFAULT_INSTANCE;
  static {
    ListHistoryArchiveRecordsRequest defaultInstance = new ListHistoryArchiveRecordsRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListHistoryArchiveRecordsRequest.class, defaultInstance);
  }

  public static com.example.messenger.proto.ListHistoryArchiveRecordsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListHistoryArchiveRecordsRequest> PARSER;

  public static com.google.protobuf.Parser<ListHistoryArchiveRecordsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

