// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeloginRequest")
public inline fun loginRequest(block: com.example.messenger.proto.LoginRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.LoginRequest =
  com.example.messenger.proto.LoginRequestKt.Dsl._create(com.example.messenger.proto.LoginRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.LoginRequest`
 */
public object LoginRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.LoginRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.LoginRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.LoginRequest = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string password = 2;`
     */
    public var password: kotlin.String
      @kotlin.jvm.JvmName("getPassword")
        get() = _builder.password
      @kotlin.jvm.JvmName("setPassword")
        set(value) {
        _builder.password = value
      }
    /**
     * `string password = 2;`
     */
    public fun clearPassword() {
      _builder.clearPassword()
    }

    /**
     * `string device_id = 3;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 3;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }
  }
}
public inline fun com.example.messenger.proto.LoginRequest.copy(block: `com.example.messenger.proto`.LoginRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.LoginRequest =
  `com.example.messenger.proto`.LoginRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

