// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface MessageDeletedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.MessageDeletedEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 message_id = 1;</code>
   * @return The messageId.
   */
  long getMessageId();

  /**
   * <code>string conversation_id = 2;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <code>string conversation_id = 2;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();
}
