// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeoneTimePrekey")
public inline fun oneTimePrekey(block: com.example.messenger.proto.OneTimePrekeyKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.OneTimePrekey =
  com.example.messenger.proto.OneTimePrekeyKt.Dsl._create(com.example.messenger.proto.OneTimePrekey.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.OneTimePrekey`
 */
public object OneTimePrekeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.OneTimePrekey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.OneTimePrekey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.OneTimePrekey = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string key_id = 2;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 2;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string algorithm = 3;`
     */
    public var algorithm: kotlin.String
      @kotlin.jvm.JvmName("getAlgorithm")
        get() = _builder.algorithm
      @kotlin.jvm.JvmName("setAlgorithm")
        set(value) {
        _builder.algorithm = value
      }
    /**
     * `string algorithm = 3;`
     */
    public fun clearAlgorithm() {
      _builder.clearAlgorithm()
    }

    /**
     * <code>bytes public_key = 4;</code>
     */
    public var publicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPublicKey")
        get() = _builder.publicKey
      @kotlin.jvm.JvmName("setPublicKey")
        set(value) {
        _builder.publicKey = value
      }
    /**
     * `bytes public_key = 4;`
     */
    public fun clearPublicKey() {
      _builder.clearPublicKey()
    }

    /**
     * `.google.protobuf.Timestamp published_at = 5;`
     */
    public var publishedAt: com.google.protobuf.Timestamp
      @kotlin.jvm.JvmName("getPublishedAt")
        get() = _builder.publishedAt
      @kotlin.jvm.JvmName("setPublishedAt")
        set(value) {
        _builder.publishedAt = value
      }
    /**
     * `.google.protobuf.Timestamp published_at = 5;`
     */
    public fun clearPublishedAt() {
      _builder.clearPublishedAt()
    }
    /**
     * `.google.protobuf.Timestamp published_at = 5;`
     * @return Whether the publishedAt field is set.
     */
    public fun hasPublishedAt(): kotlin.Boolean {
      return _builder.hasPublishedAt()
    }

    public val OneTimePrekeyKt.Dsl.publishedAtOrNull: com.google.protobuf.Timestamp?
      get() = _builder.publishedAtOrNull

    /**
     * `string device_id = 6;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 6;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }
  }
}
public inline fun com.example.messenger.proto.OneTimePrekey.copy(block: `com.example.messenger.proto`.OneTimePrekeyKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.OneTimePrekey =
  `com.example.messenger.proto`.OneTimePrekeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.messenger.proto.OneTimePrekeyOrBuilder.publishedAtOrNull: com.google.protobuf.Timestamp?
  get() = if (hasPublishedAt()) getPublishedAt() else null

