// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface OneTimePrekeyUploadOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.OneTimePrekeyUpload)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string key_id = 1;</code>
   * @return The keyId.
   */
  java.lang.String getKeyId();
  /**
   * <code>string key_id = 1;</code>
   * @return The bytes for keyId.
   */
  com.google.protobuf.ByteString
      getKeyIdBytes();

  /**
   * <code>string algorithm = 2;</code>
   * @return The algorithm.
   */
  java.lang.String getAlgorithm();
  /**
   * <code>string algorithm = 2;</code>
   * @return The bytes for algorithm.
   */
  com.google.protobuf.ByteString
      getAlgorithmBytes();

  /**
   * <code>bytes public_key = 3;</code>
   * @return The publicKey.
   */
  com.google.protobuf.ByteString getPublicKey();
}
