// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.PrekeyBundle}
 */
public  final class PrekeyBundle extends
    com.google.protobuf.GeneratedMessageLite<
        PrekeyBundle, PrekeyBundle.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.PrekeyBundle)
    PrekeyBundleOrBuilder {
  private PrekeyBundle() {
    username_ = "";
    deviceId_ = "";
  }
  private int bitField0_;
  public static final int USERNAME_FIELD_NUMBER = 1;
  private java.lang.String username_;
  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 1;</code>
   * @param value The username to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUsername(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    username_ = value;
  }
  /**
   * <code>string username = 1;</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 1;</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();

  }

  public static final int IDENTITY_KEY_FIELD_NUMBER = 2;
  private com.example.messenger.proto.IdentityKey identityKey_;
  /**
   * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
   */
  @java.lang.Override
  public boolean hasIdentityKey() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.IdentityKey getIdentityKey() {
    return identityKey_ == null ? com.example.messenger.proto.IdentityKey.getDefaultInstance() : identityKey_;
  }
  /**
   * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setIdentityKey(com.example.messenger.proto.IdentityKey value) {
    value.getClass();  // minimal bytecode null check
    identityKey_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeIdentityKey(com.example.messenger.proto.IdentityKey value) {
    value.getClass();  // minimal bytecode null check
    if (identityKey_ != null &&
        identityKey_ != com.example.messenger.proto.IdentityKey.getDefaultInstance()) {
      identityKey_ =
        com.example.messenger.proto.IdentityKey.newBuilder(identityKey_).mergeFrom(value).buildPartial();
    } else {
      identityKey_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
   */
  private void clearIdentityKey() {  identityKey_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int SIGNED_PREKEY_FIELD_NUMBER = 3;
  private com.example.messenger.proto.SignedPrekey signedPrekey_;
  /**
   * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
   */
  @java.lang.Override
  public boolean hasSignedPrekey() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.SignedPrekey getSignedPrekey() {
    return signedPrekey_ == null ? com.example.messenger.proto.SignedPrekey.getDefaultInstance() : signedPrekey_;
  }
  /**
   * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSignedPrekey(com.example.messenger.proto.SignedPrekey value) {
    value.getClass();  // minimal bytecode null check
    signedPrekey_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeSignedPrekey(com.example.messenger.proto.SignedPrekey value) {
    value.getClass();  // minimal bytecode null check
    if (signedPrekey_ != null &&
        signedPrekey_ != com.example.messenger.proto.SignedPrekey.getDefaultInstance()) {
      signedPrekey_ =
        com.example.messenger.proto.SignedPrekey.newBuilder(signedPrekey_).mergeFrom(value).buildPartial();
    } else {
      signedPrekey_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
   */
  private void clearSignedPrekey() {  signedPrekey_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int ONE_TIME_PREKEY_FIELD_NUMBER = 4;
  private com.example.messenger.proto.OneTimePrekey oneTimePrekey_;
  /**
   * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
   */
  @java.lang.Override
  public boolean hasOneTimePrekey() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.OneTimePrekey getOneTimePrekey() {
    return oneTimePrekey_ == null ? com.example.messenger.proto.OneTimePrekey.getDefaultInstance() : oneTimePrekey_;
  }
  /**
   * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setOneTimePrekey(com.example.messenger.proto.OneTimePrekey value) {
    value.getClass();  // minimal bytecode null check
    oneTimePrekey_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeOneTimePrekey(com.example.messenger.proto.OneTimePrekey value) {
    value.getClass();  // minimal bytecode null check
    if (oneTimePrekey_ != null &&
        oneTimePrekey_ != com.example.messenger.proto.OneTimePrekey.getDefaultInstance()) {
      oneTimePrekey_ =
        com.example.messenger.proto.OneTimePrekey.newBuilder(oneTimePrekey_).mergeFrom(value).buildPartial();
    } else {
      oneTimePrekey_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
   */
  private void clearOneTimePrekey() {  oneTimePrekey_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 5;
  private java.lang.String deviceId_;
  /**
   * <code>string device_id = 5;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    return deviceId_;
  }
  /**
   * <code>string device_id = 5;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(deviceId_);
  }
  /**
   * <code>string device_id = 5;</code>
   * @param value The deviceId to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDeviceId(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    deviceId_ = value;
  }
  /**
   * <code>string device_id = 5;</code>
   */
  private void clearDeviceId() {

    deviceId_ = getDefaultInstance().getDeviceId();
  }
  /**
   * <code>string device_id = 5;</code>
   * @param value The bytes for deviceId to set.
   */
  private void setDeviceIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    deviceId_ = value.toStringUtf8();

  }

  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.PrekeyBundle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.PrekeyBundle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PrekeyBundle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.PrekeyBundle prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.PrekeyBundle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.PrekeyBundle, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.PrekeyBundle)
      com.example.messenger.proto.PrekeyBundleOrBuilder {
    // Construct using com.example.messenger.proto.PrekeyBundle.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    @java.lang.Override
    public boolean hasIdentityKey() {
      return instance.hasIdentityKey();
    }
    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.IdentityKey getIdentityKey() {
      return instance.getIdentityKey();
    }
    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    public Builder setIdentityKey(com.example.messenger.proto.IdentityKey value) {
      copyOnWrite();
      instance.setIdentityKey(value);
      return this;
      }
    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    public Builder setIdentityKey(
        com.example.messenger.proto.IdentityKey.Builder builderForValue) {
      copyOnWrite();
      instance.setIdentityKey(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    public Builder mergeIdentityKey(com.example.messenger.proto.IdentityKey value) {
      copyOnWrite();
      instance.mergeIdentityKey(value);
      return this;
    }
    /**
     * <code>.messenger.v1.IdentityKey identity_key = 2;</code>
     */
    public Builder clearIdentityKey() {  copyOnWrite();
      instance.clearIdentityKey();
      return this;
    }

    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    @java.lang.Override
    public boolean hasSignedPrekey() {
      return instance.hasSignedPrekey();
    }
    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.SignedPrekey getSignedPrekey() {
      return instance.getSignedPrekey();
    }
    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    public Builder setSignedPrekey(com.example.messenger.proto.SignedPrekey value) {
      copyOnWrite();
      instance.setSignedPrekey(value);
      return this;
      }
    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    public Builder setSignedPrekey(
        com.example.messenger.proto.SignedPrekey.Builder builderForValue) {
      copyOnWrite();
      instance.setSignedPrekey(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    public Builder mergeSignedPrekey(com.example.messenger.proto.SignedPrekey value) {
      copyOnWrite();
      instance.mergeSignedPrekey(value);
      return this;
    }
    /**
     * <code>.messenger.v1.SignedPrekey signed_prekey = 3;</code>
     */
    public Builder clearSignedPrekey() {  copyOnWrite();
      instance.clearSignedPrekey();
      return this;
    }

    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    @java.lang.Override
    public boolean hasOneTimePrekey() {
      return instance.hasOneTimePrekey();
    }
    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.OneTimePrekey getOneTimePrekey() {
      return instance.getOneTimePrekey();
    }
    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    public Builder setOneTimePrekey(com.example.messenger.proto.OneTimePrekey value) {
      copyOnWrite();
      instance.setOneTimePrekey(value);
      return this;
      }
    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    public Builder setOneTimePrekey(
        com.example.messenger.proto.OneTimePrekey.Builder builderForValue) {
      copyOnWrite();
      instance.setOneTimePrekey(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    public Builder mergeOneTimePrekey(com.example.messenger.proto.OneTimePrekey value) {
      copyOnWrite();
      instance.mergeOneTimePrekey(value);
      return this;
    }
    /**
     * <code>.messenger.v1.OneTimePrekey one_time_prekey = 4;</code>
     */
    public Builder clearOneTimePrekey() {  copyOnWrite();
      instance.clearOneTimePrekey();
      return this;
    }

    /**
     * <code>string device_id = 5;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      return instance.getDeviceId();
    }
    /**
     * <code>string device_id = 5;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      return instance.getDeviceIdBytes();
    }
    /**
     * <code>string device_id = 5;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDeviceId(value);
      return this;
    }
    /**
     * <code>string device_id = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      copyOnWrite();
      instance.clearDeviceId();
      return this;
    }
    /**
     * <code>string device_id = 5;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDeviceIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.PrekeyBundle)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.PrekeyBundle();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "username_",
            "identityKey_",
            "signedPrekey_",
            "oneTimePrekey_",
            "deviceId_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0001\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000\u0003\u1009\u0001\u0004\u1009\u0002\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.PrekeyBundle> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.PrekeyBundle.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.PrekeyBundle>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.PrekeyBundle)
  private static final com.example.messenger.proto.PrekeyBundle DEFAULT_INSTANCE;
  static {
    PrekeyBundle defaultInstance = new PrekeyBundle();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PrekeyBundle.class, defaultInstance);
  }

  public static com.example.messenger.proto.PrekeyBundle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PrekeyBundle> PARSER;

  public static com.google.protobuf.Parser<PrekeyBundle> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

