// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.PrepareMediaUploadRequest}
 */
public  final class PrepareMediaUploadRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PrepareMediaUploadRequest, PrepareMediaUploadRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.PrepareMediaUploadRequest)
    PrepareMediaUploadRequestOrBuilder {
  private PrepareMediaUploadRequest() {
    filename_ = "";
    mimeType_ = "";
  }
  public static final int FILENAME_FIELD_NUMBER = 1;
  private java.lang.String filename_;
  /**
   * <code>string filename = 1;</code>
   * @return The filename.
   */
  @java.lang.Override
  public java.lang.String getFilename() {
    return filename_;
  }
  /**
   * <code>string filename = 1;</code>
   * @return The bytes for filename.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(filename_);
  }
  /**
   * <code>string filename = 1;</code>
   * @param value The filename to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setFilename(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    filename_ = value;
  }
  /**
   * <code>string filename = 1;</code>
   */
  private void clearFilename() {

    filename_ = getDefaultInstance().getFilename();
  }
  /**
   * <code>string filename = 1;</code>
   * @param value The bytes for filename to set.
   */
  private void setFilenameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    filename_ = value.toStringUtf8();

  }

  public static final int MIME_TYPE_FIELD_NUMBER = 2;
  private java.lang.String mimeType_;
  /**
   * <code>string mime_type = 2;</code>
   * @return The mimeType.
   */
  @java.lang.Override
  public java.lang.String getMimeType() {
    return mimeType_;
  }
  /**
   * <code>string mime_type = 2;</code>
   * @return The bytes for mimeType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(mimeType_);
  }
  /**
   * <code>string mime_type = 2;</code>
   * @param value The mimeType to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMimeType(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    mimeType_ = value;
  }
  /**
   * <code>string mime_type = 2;</code>
   */
  private void clearMimeType() {

    mimeType_ = getDefaultInstance().getMimeType();
  }
  /**
   * <code>string mime_type = 2;</code>
   * @param value The bytes for mimeType to set.
   */
  private void setMimeTypeBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    mimeType_ = value.toStringUtf8();

  }

  public static final int SIZE_BYTES_FIELD_NUMBER = 3;
  private long sizeBytes_;
  /**
   * <code>int64 size_bytes = 3;</code>
   * @return The sizeBytes.
   */
  @java.lang.Override
  public long getSizeBytes() {
    return sizeBytes_;
  }
  /**
   * <code>int64 size_bytes = 3;</code>
   * @param value The sizeBytes to set.
   */
  private void setSizeBytes(long value) {
    
    sizeBytes_ = value;
  }
  /**
   * <code>int64 size_bytes = 3;</code>
   */
  private void clearSizeBytes() {

    sizeBytes_ = 0L;
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private int kind_;
  /**
   * <code>.messenger.v1.AttachmentKind kind = 4;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override
  public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.messenger.v1.AttachmentKind kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public com.example.messenger.proto.AttachmentKind getKind() {
    com.example.messenger.proto.AttachmentKind result = com.example.messenger.proto.AttachmentKind.forNumber(kind_);
    return result == null ? com.example.messenger.proto.AttachmentKind.UNRECOGNIZED : result;
  }
  /**
   * <code>.messenger.v1.AttachmentKind kind = 4;</code>
   * @param value The enum numeric value on the wire for kind to set.
   */
  private void setKindValue(int value) {
      kind_ = value;
  }
  /**
   * <code>.messenger.v1.AttachmentKind kind = 4;</code>
   * @param value The kind to set.
   */
  private void setKind(com.example.messenger.proto.AttachmentKind value) {
    kind_ = value.getNumber();

  }
  /**
   * <code>.messenger.v1.AttachmentKind kind = 4;</code>
   */
  private void clearKind() {

    kind_ = 0;
  }

  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.PrepareMediaUploadRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.PrepareMediaUploadRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PrepareMediaUploadRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.PrepareMediaUploadRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.PrepareMediaUploadRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.PrepareMediaUploadRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.PrepareMediaUploadRequest)
      com.example.messenger.proto.PrepareMediaUploadRequestOrBuilder {
    // Construct using com.example.messenger.proto.PrepareMediaUploadRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string filename = 1;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      return instance.getFilename();
    }
    /**
     * <code>string filename = 1;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      return instance.getFilenameBytes();
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilename(
        java.lang.String value) {
      copyOnWrite();
      instance.setFilename(value);
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFilename() {
      copyOnWrite();
      instance.clearFilename();
      return this;
    }
    /**
     * <code>string filename = 1;</code>
     * @param value The bytes for filename to set.
     * @return This builder for chaining.
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFilenameBytes(value);
      return this;
    }

    /**
     * <code>string mime_type = 2;</code>
     * @return The mimeType.
     */
    @java.lang.Override
    public java.lang.String getMimeType() {
      return instance.getMimeType();
    }
    /**
     * <code>string mime_type = 2;</code>
     * @return The bytes for mimeType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      return instance.getMimeTypeBytes();
    }
    /**
     * <code>string mime_type = 2;</code>
     * @param value The mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeType(
        java.lang.String value) {
      copyOnWrite();
      instance.setMimeType(value);
      return this;
    }
    /**
     * <code>string mime_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMimeType() {
      copyOnWrite();
      instance.clearMimeType();
      return this;
    }
    /**
     * <code>string mime_type = 2;</code>
     * @param value The bytes for mimeType to set.
     * @return This builder for chaining.
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMimeTypeBytes(value);
      return this;
    }

    /**
     * <code>int64 size_bytes = 3;</code>
     * @return The sizeBytes.
     */
    @java.lang.Override
    public long getSizeBytes() {
      return instance.getSizeBytes();
    }
    /**
     * <code>int64 size_bytes = 3;</code>
     * @param value The sizeBytes to set.
     * @return This builder for chaining.
     */
    public Builder setSizeBytes(long value) {
      copyOnWrite();
      instance.setSizeBytes(value);
      return this;
    }
    /**
     * <code>int64 size_bytes = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSizeBytes() {
      copyOnWrite();
      instance.clearSizeBytes();
      return this;
    }

    /**
     * <code>.messenger.v1.AttachmentKind kind = 4;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override
    public int getKindValue() {
      return instance.getKindValue();
    }
    /**
     * <code>.messenger.v1.AttachmentKind kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      copyOnWrite();
      instance.setKindValue(value);
      return this;
    }
    /**
     * <code>.messenger.v1.AttachmentKind kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public com.example.messenger.proto.AttachmentKind getKind() {
      return instance.getKind();
    }
    /**
     * <code>.messenger.v1.AttachmentKind kind = 4;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(com.example.messenger.proto.AttachmentKind value) {
      copyOnWrite();
      instance.setKind(value);
      return this;
    }
    /**
     * <code>.messenger.v1.AttachmentKind kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      copyOnWrite();
      instance.clearKind();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.PrepareMediaUploadRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.PrepareMediaUploadRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "filename_",
            "mimeType_",
            "sizeBytes_",
            "kind_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0002\u0004\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.PrepareMediaUploadRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.PrepareMediaUploadRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.PrepareMediaUploadRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.PrepareMediaUploadRequest)
  private static final com.example.messenger.proto.PrepareMediaUploadRequest DEFAULT_INSTANCE;
  static {
    PrepareMediaUploadRequest defaultInstance = new PrepareMediaUploadRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PrepareMediaUploadRequest.class, defaultInstance);
  }

  public static com.example.messenger.proto.PrepareMediaUploadRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PrepareMediaUploadRequest> PARSER;

  public static com.google.protobuf.Parser<PrepareMediaUploadRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

