// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.PresenceEvent}
 */
public  final class PresenceEvent extends
    com.google.protobuf.GeneratedMessageLite<
        PresenceEvent, PresenceEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.PresenceEvent)
    PresenceEventOrBuilder {
  private PresenceEvent() {
    onlineUsers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int ONLINE_USERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> onlineUsers_;
  /**
   * <code>repeated string online_users = 1;</code>
   * @return A list containing the onlineUsers.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getOnlineUsersList() {
    return onlineUsers_;
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @return The count of onlineUsers.
   */
  @java.lang.Override
  public int getOnlineUsersCount() {
    return onlineUsers_.size();
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param index The index of the element to return.
   * @return The onlineUsers at the given index.
   */
  @java.lang.Override
  public java.lang.String getOnlineUsers(int index) {
    return onlineUsers_.get(index);
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the onlineUsers at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOnlineUsersBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        onlineUsers_.get(index));
  }
  private void ensureOnlineUsersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        onlineUsers_;  if (!tmp.isModifiable()) {
      onlineUsers_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param index The index to set the value at.
   * @param value The onlineUsers to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setOnlineUsers(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureOnlineUsersIsMutable();
    onlineUsers_.set(index, value);
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param value The onlineUsers to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addOnlineUsers(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureOnlineUsersIsMutable();
    onlineUsers_.add(value);
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param values The onlineUsers to add.
   */
  private void addAllOnlineUsers(
      java.lang.Iterable<java.lang.String> values) {
    ensureOnlineUsersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, onlineUsers_);
  }
  /**
   * <code>repeated string online_users = 1;</code>
   */
  private void clearOnlineUsers() {
    onlineUsers_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string online_users = 1;</code>
   * @param value The bytes of the onlineUsers to add.
   */
  private void addOnlineUsersBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureOnlineUsersIsMutable();
    onlineUsers_.add(value.toStringUtf8());
  }

  public static com.example.messenger.proto.PresenceEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.PresenceEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.PresenceEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.PresenceEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.PresenceEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.PresenceEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.PresenceEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.PresenceEvent)
      com.example.messenger.proto.PresenceEventOrBuilder {
    // Construct using com.example.messenger.proto.PresenceEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string online_users = 1;</code>
     * @return A list containing the onlineUsers.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getOnlineUsersList() {
      return java.util.Collections.unmodifiableList(
          instance.getOnlineUsersList());
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @return The count of onlineUsers.
     */
    @java.lang.Override
    public int getOnlineUsersCount() {
      return instance.getOnlineUsersCount();
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param index The index of the element to return.
     * @return The onlineUsers at the given index.
     */
    @java.lang.Override
    public java.lang.String getOnlineUsers(int index) {
      return instance.getOnlineUsers(index);
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the onlineUsers at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOnlineUsersBytes(int index) {
      return instance.getOnlineUsersBytes(index);
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param index The index to set the value at.
     * @param value The onlineUsers to set.
     * @return This builder for chaining.
     */
    public Builder setOnlineUsers(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setOnlineUsers(index, value);
      return this;
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param value The onlineUsers to add.
     * @return This builder for chaining.
     */
    public Builder addOnlineUsers(
        java.lang.String value) {
      copyOnWrite();
      instance.addOnlineUsers(value);
      return this;
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param values The onlineUsers to add.
     * @return This builder for chaining.
     */
    public Builder addAllOnlineUsers(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllOnlineUsers(values);
      return this;
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlineUsers() {
      copyOnWrite();
      instance.clearOnlineUsers();
      return this;
    }
    /**
     * <code>repeated string online_users = 1;</code>
     * @param value The bytes of the onlineUsers to add.
     * @return This builder for chaining.
     */
    public Builder addOnlineUsersBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addOnlineUsersBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.PresenceEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.PresenceEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "onlineUsers_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.PresenceEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.PresenceEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.PresenceEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.PresenceEvent)
  private static final com.example.messenger.proto.PresenceEvent DEFAULT_INSTANCE;
  static {
    PresenceEvent defaultInstance = new PresenceEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PresenceEvent.class, defaultInstance);
  }

  public static com.example.messenger.proto.PresenceEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PresenceEvent> PARSER;

  public static com.google.protobuf.Parser<PresenceEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

