// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface ProfileEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.ProfileEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   * @return Whether the profile field is set.
   */
  boolean hasProfile();
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   * @return The profile.
   */
  com.example.messenger.proto.Profile getProfile();
}
