// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeprofileEvent")
public inline fun profileEvent(block: com.example.messenger.proto.ProfileEventKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ProfileEvent =
  com.example.messenger.proto.ProfileEventKt.Dsl._create(com.example.messenger.proto.ProfileEvent.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.ProfileEvent`
 */
public object ProfileEventKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.ProfileEvent.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.ProfileEvent.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.ProfileEvent = _builder.build()

    /**
     * `.messenger.v1.Profile profile = 1;`
     */
    public var profile: com.example.messenger.proto.Profile
      @kotlin.jvm.JvmName("getProfile")
        get() = _builder.profile
      @kotlin.jvm.JvmName("setProfile")
        set(value) {
        _builder.profile = value
      }
    /**
     * `.messenger.v1.Profile profile = 1;`
     */
    public fun clearProfile() {
      _builder.clearProfile()
    }
    /**
     * `.messenger.v1.Profile profile = 1;`
     * @return Whether the profile field is set.
     */
    public fun hasProfile(): kotlin.Boolean {
      return _builder.hasProfile()
    }

    public val ProfileEventKt.Dsl.profileOrNull: com.example.messenger.proto.Profile?
      get() = _builder.profileOrNull
  }
}
public inline fun com.example.messenger.proto.ProfileEvent.copy(block: `com.example.messenger.proto`.ProfileEventKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.ProfileEvent =
  `com.example.messenger.proto`.ProfileEventKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.messenger.proto.ProfileEventOrBuilder.profileOrNull: com.example.messenger.proto.Profile?
  get() = if (hasProfile()) getProfile() else null

