// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.ProfileEvent}
 */
public  final class ProfileEvent extends
    com.google.protobuf.GeneratedMessageLite<
        ProfileEvent, ProfileEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.ProfileEvent)
    ProfileEventOrBuilder {
  private ProfileEvent() {
  }
  private int bitField0_;
  public static final int PROFILE_FIELD_NUMBER = 1;
  private com.example.messenger.proto.Profile profile_;
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   */
  @java.lang.Override
  public boolean hasProfile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.Profile getProfile() {
    return profile_ == null ? com.example.messenger.proto.Profile.getDefaultInstance() : profile_;
  }
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setProfile(com.example.messenger.proto.Profile value) {
    value.getClass();  // minimal bytecode null check
    profile_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeProfile(com.example.messenger.proto.Profile value) {
    value.getClass();  // minimal bytecode null check
    if (profile_ != null &&
        profile_ != com.example.messenger.proto.Profile.getDefaultInstance()) {
      profile_ =
        com.example.messenger.proto.Profile.newBuilder(profile_).mergeFrom(value).buildPartial();
    } else {
      profile_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.messenger.v1.Profile profile = 1;</code>
   */
  private void clearProfile() {  profile_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.example.messenger.proto.ProfileEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.ProfileEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.ProfileEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ProfileEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.ProfileEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.ProfileEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.ProfileEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.ProfileEvent)
      com.example.messenger.proto.ProfileEventOrBuilder {
    // Construct using com.example.messenger.proto.ProfileEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    @java.lang.Override
    public boolean hasProfile() {
      return instance.hasProfile();
    }
    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.Profile getProfile() {
      return instance.getProfile();
    }
    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    public Builder setProfile(com.example.messenger.proto.Profile value) {
      copyOnWrite();
      instance.setProfile(value);
      return this;
      }
    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    public Builder setProfile(
        com.example.messenger.proto.Profile.Builder builderForValue) {
      copyOnWrite();
      instance.setProfile(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    public Builder mergeProfile(com.example.messenger.proto.Profile value) {
      copyOnWrite();
      instance.mergeProfile(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Profile profile = 1;</code>
     */
    public Builder clearProfile() {  copyOnWrite();
      instance.clearProfile();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.ProfileEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.ProfileEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "profile_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0001\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.ProfileEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.ProfileEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.ProfileEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.ProfileEvent)
  private static final com.example.messenger.proto.ProfileEvent DEFAULT_INSTANCE;
  static {
    ProfileEvent defaultInstance = new ProfileEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ProfileEvent.class, defaultInstance);
  }

  public static com.example.messenger.proto.ProfileEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ProfileEvent> PARSER;

  public static com.google.protobuf.Parser<ProfileEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

