// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializeprofile")
public inline fun profile(block: com.example.messenger.proto.ProfileKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.Profile =
  com.example.messenger.proto.ProfileKt.Dsl._create(com.example.messenger.proto.Profile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.Profile`
 */
public object ProfileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.Profile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.Profile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.Profile = _builder.build()

    /**
     * `string username = 1;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 1;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string first_name = 2;`
     */
    public var firstName: kotlin.String
      @kotlin.jvm.JvmName("getFirstName")
        get() = _builder.firstName
      @kotlin.jvm.JvmName("setFirstName")
        set(value) {
        _builder.firstName = value
      }
    /**
     * `string first_name = 2;`
     */
    public fun clearFirstName() {
      _builder.clearFirstName()
    }

    /**
     * `string last_name = 3;`
     */
    public var lastName: kotlin.String
      @kotlin.jvm.JvmName("getLastName")
        get() = _builder.lastName
      @kotlin.jvm.JvmName("setLastName")
        set(value) {
        _builder.lastName = value
      }
    /**
     * `string last_name = 3;`
     */
    public fun clearLastName() {
      _builder.clearLastName()
    }

    /**
     * `string avatar_hex = 4;`
     */
    public var avatarHex: kotlin.String
      @kotlin.jvm.JvmName("getAvatarHex")
        get() = _builder.avatarHex
      @kotlin.jvm.JvmName("setAvatarHex")
        set(value) {
        _builder.avatarHex = value
      }
    /**
     * `string avatar_hex = 4;`
     */
    public fun clearAvatarHex() {
      _builder.clearAvatarHex()
    }

    /**
     * `string avatar_data = 5;`
     */
    public var avatarData: kotlin.String
      @kotlin.jvm.JvmName("getAvatarData")
        get() = _builder.avatarData
      @kotlin.jvm.JvmName("setAvatarData")
        set(value) {
        _builder.avatarData = value
      }
    /**
     * `string avatar_data = 5;`
     */
    public fun clearAvatarData() {
      _builder.clearAvatarData()
    }
  }
}
public inline fun com.example.messenger.proto.Profile.copy(block: `com.example.messenger.proto`.ProfileKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.Profile =
  `com.example.messenger.proto`.ProfileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

