// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializepublishPrekeyBundleRequest")
public inline fun publishPrekeyBundleRequest(block: com.example.messenger.proto.PublishPrekeyBundleRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.PublishPrekeyBundleRequest =
  com.example.messenger.proto.PublishPrekeyBundleRequestKt.Dsl._create(com.example.messenger.proto.PublishPrekeyBundleRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.PublishPrekeyBundleRequest`
 */
public object PublishPrekeyBundleRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.PublishPrekeyBundleRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.PublishPrekeyBundleRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.PublishPrekeyBundleRequest = _builder.build()

    /**
     * `string signed_prekey_id = 1;`
     */
    public var signedPrekeyId: kotlin.String
      @kotlin.jvm.JvmName("getSignedPrekeyId")
        get() = _builder.signedPrekeyId
      @kotlin.jvm.JvmName("setSignedPrekeyId")
        set(value) {
        _builder.signedPrekeyId = value
      }
    /**
     * `string signed_prekey_id = 1;`
     */
    public fun clearSignedPrekeyId() {
      _builder.clearSignedPrekeyId()
    }

    /**
     * `string signed_prekey_algorithm = 2;`
     */
    public var signedPrekeyAlgorithm: kotlin.String
      @kotlin.jvm.JvmName("getSignedPrekeyAlgorithm")
        get() = _builder.signedPrekeyAlgorithm
      @kotlin.jvm.JvmName("setSignedPrekeyAlgorithm")
        set(value) {
        _builder.signedPrekeyAlgorithm = value
      }
    /**
     * `string signed_prekey_algorithm = 2;`
     */
    public fun clearSignedPrekeyAlgorithm() {
      _builder.clearSignedPrekeyAlgorithm()
    }

    /**
     * <code>bytes signed_prekey_public_key = 3;</code>
     */
    public var signedPrekeyPublicKey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSignedPrekeyPublicKey")
        get() = _builder.signedPrekeyPublicKey
      @kotlin.jvm.JvmName("setSignedPrekeyPublicKey")
        set(value) {
        _builder.signedPrekeyPublicKey = value
      }
    /**
     * `bytes signed_prekey_public_key = 3;`
     */
    public fun clearSignedPrekeyPublicKey() {
      _builder.clearSignedPrekeyPublicKey()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class OneTimePrekeysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     */
     public val oneTimePrekeys: com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.oneTimePrekeysList
      )
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     * @param value The oneTimePrekeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addOneTimePrekeys")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.add(value: com.example.messenger.proto.OneTimePrekeyUpload) {
      _builder.addOneTimePrekeys(value)
    }
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     * @param value The oneTimePrekeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignOneTimePrekeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.plusAssign(value: com.example.messenger.proto.OneTimePrekeyUpload) {
      add(value)
    }
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     * @param values The oneTimePrekeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllOneTimePrekeys")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.addAll(values: kotlin.collections.Iterable<com.example.messenger.proto.OneTimePrekeyUpload>) {
      _builder.addAllOneTimePrekeys(values)
    }
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     * @param values The oneTimePrekeys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllOneTimePrekeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.plusAssign(values: kotlin.collections.Iterable<com.example.messenger.proto.OneTimePrekeyUpload>) {
      addAll(values)
    }
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     * @param index The index to set the value at.
     * @param value The oneTimePrekeys to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setOneTimePrekeys")
    public operator fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.set(index: kotlin.Int, value: com.example.messenger.proto.OneTimePrekeyUpload) {
      _builder.setOneTimePrekeys(index, value)
    }
    /**
     * `repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearOneTimePrekeys")
    public fun com.google.protobuf.kotlin.DslList<com.example.messenger.proto.OneTimePrekeyUpload, OneTimePrekeysProxy>.clear() {
      _builder.clearOneTimePrekeys()
    }
  }
}
public inline fun com.example.messenger.proto.PublishPrekeyBundleRequest.copy(block: `com.example.messenger.proto`.PublishPrekeyBundleRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.PublishPrekeyBundleRequest =
  `com.example.messenger.proto`.PublishPrekeyBundleRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

