// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface PublishPrekeyBundleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.PublishPrekeyBundleRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string signed_prekey_id = 1;</code>
   * @return The signedPrekeyId.
   */
  java.lang.String getSignedPrekeyId();
  /**
   * <code>string signed_prekey_id = 1;</code>
   * @return The bytes for signedPrekeyId.
   */
  com.google.protobuf.ByteString
      getSignedPrekeyIdBytes();

  /**
   * <code>string signed_prekey_algorithm = 2;</code>
   * @return The signedPrekeyAlgorithm.
   */
  java.lang.String getSignedPrekeyAlgorithm();
  /**
   * <code>string signed_prekey_algorithm = 2;</code>
   * @return The bytes for signedPrekeyAlgorithm.
   */
  com.google.protobuf.ByteString
      getSignedPrekeyAlgorithmBytes();

  /**
   * <code>bytes signed_prekey_public_key = 3;</code>
   * @return The signedPrekeyPublicKey.
   */
  com.google.protobuf.ByteString getSignedPrekeyPublicKey();

  /**
   * <code>repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;</code>
   */
  java.util.List<com.example.messenger.proto.OneTimePrekeyUpload> 
      getOneTimePrekeysList();
  /**
   * <code>repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;</code>
   */
  com.example.messenger.proto.OneTimePrekeyUpload getOneTimePrekeys(int index);
  /**
   * <code>repeated .messenger.v1.OneTimePrekeyUpload one_time_prekeys = 4;</code>
   */
  int getOneTimePrekeysCount();

  /**
   * <code>bytes signed_prekey_signature = 5;</code>
   * @return The signedPrekeySignature.
   */
  com.google.protobuf.ByteString getSignedPrekeySignature();

  /**
   * <code>string signed_prekey_signature_algorithm = 6;</code>
   * @return The signedPrekeySignatureAlgorithm.
   */
  java.lang.String getSignedPrekeySignatureAlgorithm();
  /**
   * <code>string signed_prekey_signature_algorithm = 6;</code>
   * @return The bytes for signedPrekeySignatureAlgorithm.
   */
  com.google.protobuf.ByteString
      getSignedPrekeySignatureAlgorithmBytes();
}
