// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializesearchUsersRequest")
public inline fun searchUsersRequest(block: com.example.messenger.proto.SearchUsersRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.SearchUsersRequest =
  com.example.messenger.proto.SearchUsersRequestKt.Dsl._create(com.example.messenger.proto.SearchUsersRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.SearchUsersRequest`
 */
public object SearchUsersRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.SearchUsersRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.SearchUsersRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.SearchUsersRequest = _builder.build()

    /**
     * `string query = 1;`
     */
    public var query: kotlin.String
      @kotlin.jvm.JvmName("getQuery")
        get() = _builder.query
      @kotlin.jvm.JvmName("setQuery")
        set(value) {
        _builder.query = value
      }
    /**
     * `string query = 1;`
     */
    public fun clearQuery() {
      _builder.clearQuery()
    }

    /**
     * <code>int32 limit = 2;</code>
     */
    public var limit: kotlin.Int
      @kotlin.jvm.JvmName("getLimit")
        get() = _builder.limit
      @kotlin.jvm.JvmName("setLimit")
        set(value) {
        _builder.limit = value
      }
    /**
     * `int32 limit = 2;`
     */
    public fun clearLimit() {
      _builder.clearLimit()
    }
  }
}
public inline fun com.example.messenger.proto.SearchUsersRequest.copy(block: `com.example.messenger.proto`.SearchUsersRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.SearchUsersRequest =
  `com.example.messenger.proto`.SearchUsersRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

