// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

/**
 * Protobuf type {@code messenger.v1.ServerEvent}
 */
public  final class ServerEvent extends
    com.google.protobuf.GeneratedMessageLite<
        ServerEvent, ServerEvent.Builder> implements
    // @@protoc_insertion_point(message_implements:messenger.v1.ServerEvent)
    ServerEventOrBuilder {
  private ServerEvent() {
  }
  private int bitField0_;
  private int payloadCase_ = 0;
  private java.lang.Object payload_;
  public enum PayloadCase {
    PRESENCE(2),
    MESSAGE(3),
    PROFILE(4),
    MESSAGE_DELETED(5),
    CONVERSATION(6),
    CONVERSATION_REMOVED(7),
    PAYLOAD_NOT_SET(0);
    private final int value;
    private PayloadCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PayloadCase valueOf(int value) {
      return forNumber(value);
    }

    public static PayloadCase forNumber(int value) {
      switch (value) {
        case 2: return PRESENCE;
        case 3: return MESSAGE;
        case 4: return PROFILE;
        case 5: return MESSAGE_DELETED;
        case 6: return CONVERSATION;
        case 7: return CONVERSATION_REMOVED;
        case 0: return PAYLOAD_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public PayloadCase
  getPayloadCase() {
    return PayloadCase.forNumber(
        payloadCase_);
  }

  private void clearPayload() {
    payloadCase_ = 0;
    payload_ = null;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  @java.lang.Override
  public boolean hasCreatedAt() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setCreatedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    createdAt_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeCreatedAt(com.google.protobuf.Timestamp value) {
    value.getClass();  // minimal bytecode null check
    if (createdAt_ != null &&
        createdAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
      createdAt_ =
        com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
    } else {
      createdAt_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.Timestamp created_at = 1;</code>
   */
  private void clearCreatedAt() {  createdAt_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int PRESENCE_FIELD_NUMBER = 2;
  /**
   * <code>.messenger.v1.PresenceEvent presence = 2;</code>
   */
  @java.lang.Override
  public boolean hasPresence() {
    return payloadCase_ == 2;
  }
  /**
   * <code>.messenger.v1.PresenceEvent presence = 2;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.PresenceEvent getPresence() {
    if (payloadCase_ == 2) {
       return (com.example.messenger.proto.PresenceEvent) payload_;
    }
    return com.example.messenger.proto.PresenceEvent.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.PresenceEvent presence = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPresence(com.example.messenger.proto.PresenceEvent value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 2;
  }
  /**
   * <code>.messenger.v1.PresenceEvent presence = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergePresence(com.example.messenger.proto.PresenceEvent value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 2 &&
        payload_ != com.example.messenger.proto.PresenceEvent.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.PresenceEvent.newBuilder((com.example.messenger.proto.PresenceEvent) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 2;
  }
  /**
   * <code>.messenger.v1.PresenceEvent presence = 2;</code>
   */
  private void clearPresence() {
    if (payloadCase_ == 2) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>.messenger.v1.Message message = 3;</code>
   */
  @java.lang.Override
  public boolean hasMessage() {
    return payloadCase_ == 3;
  }
  /**
   * <code>.messenger.v1.Message message = 3;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.Message getMessage() {
    if (payloadCase_ == 3) {
       return (com.example.messenger.proto.Message) payload_;
    }
    return com.example.messenger.proto.Message.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.Message message = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMessage(com.example.messenger.proto.Message value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 3;
  }
  /**
   * <code>.messenger.v1.Message message = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeMessage(com.example.messenger.proto.Message value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 3 &&
        payload_ != com.example.messenger.proto.Message.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.Message.newBuilder((com.example.messenger.proto.Message) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 3;
  }
  /**
   * <code>.messenger.v1.Message message = 3;</code>
   */
  private void clearMessage() {
    if (payloadCase_ == 3) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int PROFILE_FIELD_NUMBER = 4;
  /**
   * <code>.messenger.v1.ProfileEvent profile = 4;</code>
   */
  @java.lang.Override
  public boolean hasProfile() {
    return payloadCase_ == 4;
  }
  /**
   * <code>.messenger.v1.ProfileEvent profile = 4;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.ProfileEvent getProfile() {
    if (payloadCase_ == 4) {
       return (com.example.messenger.proto.ProfileEvent) payload_;
    }
    return com.example.messenger.proto.ProfileEvent.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.ProfileEvent profile = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setProfile(com.example.messenger.proto.ProfileEvent value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 4;
  }
  /**
   * <code>.messenger.v1.ProfileEvent profile = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeProfile(com.example.messenger.proto.ProfileEvent value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 4 &&
        payload_ != com.example.messenger.proto.ProfileEvent.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.ProfileEvent.newBuilder((com.example.messenger.proto.ProfileEvent) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 4;
  }
  /**
   * <code>.messenger.v1.ProfileEvent profile = 4;</code>
   */
  private void clearProfile() {
    if (payloadCase_ == 4) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int MESSAGE_DELETED_FIELD_NUMBER = 5;
  /**
   * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
   */
  @java.lang.Override
  public boolean hasMessageDeleted() {
    return payloadCase_ == 5;
  }
  /**
   * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.MessageDeletedEvent getMessageDeleted() {
    if (payloadCase_ == 5) {
       return (com.example.messenger.proto.MessageDeletedEvent) payload_;
    }
    return com.example.messenger.proto.MessageDeletedEvent.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMessageDeleted(com.example.messenger.proto.MessageDeletedEvent value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 5;
  }
  /**
   * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeMessageDeleted(com.example.messenger.proto.MessageDeletedEvent value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 5 &&
        payload_ != com.example.messenger.proto.MessageDeletedEvent.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.MessageDeletedEvent.newBuilder((com.example.messenger.proto.MessageDeletedEvent) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 5;
  }
  /**
   * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
   */
  private void clearMessageDeleted() {
    if (payloadCase_ == 5) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int CONVERSATION_FIELD_NUMBER = 6;
  /**
   * <code>.messenger.v1.Conversation conversation = 6;</code>
   */
  @java.lang.Override
  public boolean hasConversation() {
    return payloadCase_ == 6;
  }
  /**
   * <code>.messenger.v1.Conversation conversation = 6;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.Conversation getConversation() {
    if (payloadCase_ == 6) {
       return (com.example.messenger.proto.Conversation) payload_;
    }
    return com.example.messenger.proto.Conversation.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.Conversation conversation = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setConversation(com.example.messenger.proto.Conversation value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 6;
  }
  /**
   * <code>.messenger.v1.Conversation conversation = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeConversation(com.example.messenger.proto.Conversation value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 6 &&
        payload_ != com.example.messenger.proto.Conversation.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.Conversation.newBuilder((com.example.messenger.proto.Conversation) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 6;
  }
  /**
   * <code>.messenger.v1.Conversation conversation = 6;</code>
   */
  private void clearConversation() {
    if (payloadCase_ == 6) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static final int CONVERSATION_REMOVED_FIELD_NUMBER = 7;
  /**
   * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
   */
  @java.lang.Override
  public boolean hasConversationRemoved() {
    return payloadCase_ == 7;
  }
  /**
   * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
   */
  @java.lang.Override
  public com.example.messenger.proto.ConversationRemovedEvent getConversationRemoved() {
    if (payloadCase_ == 7) {
       return (com.example.messenger.proto.ConversationRemovedEvent) payload_;
    }
    return com.example.messenger.proto.ConversationRemovedEvent.getDefaultInstance();
  }
  /**
   * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setConversationRemoved(com.example.messenger.proto.ConversationRemovedEvent value) {
    value.getClass();  // minimal bytecode null check
    payload_ = value;
    payloadCase_ = 7;
  }
  /**
   * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void mergeConversationRemoved(com.example.messenger.proto.ConversationRemovedEvent value) {
    value.getClass();  // minimal bytecode null check
    if (payloadCase_ == 7 &&
        payload_ != com.example.messenger.proto.ConversationRemovedEvent.getDefaultInstance()) {
      payload_ = com.example.messenger.proto.ConversationRemovedEvent.newBuilder((com.example.messenger.proto.ConversationRemovedEvent) payload_)
          .mergeFrom(value).buildPartial();
    } else {
      payload_ = value;
    }
    payloadCase_ = 7;
  }
  /**
   * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
   */
  private void clearConversationRemoved() {
    if (payloadCase_ == 7) {
      payloadCase_ = 0;
      payload_ = null;
    }
  }

  public static com.example.messenger.proto.ServerEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.example.messenger.proto.ServerEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.example.messenger.proto.ServerEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.messenger.proto.ServerEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.messenger.proto.ServerEvent prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code messenger.v1.ServerEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.messenger.proto.ServerEvent, Builder> implements
      // @@protoc_insertion_point(builder_implements:messenger.v1.ServerEvent)
      com.example.messenger.proto.ServerEventOrBuilder {
    // Construct using com.example.messenger.proto.ServerEvent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public PayloadCase
        getPayloadCase() {
      return instance.getPayloadCase();
    }

    public Builder clearPayload() {
      copyOnWrite();
      instance.clearPayload();
      return this;
    }


    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    @java.lang.Override
    public boolean hasCreatedAt() {
      return instance.hasCreatedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCreatedAt() {
      return instance.getCreatedAt();
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.setCreatedAt(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      copyOnWrite();
      instance.setCreatedAt(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      copyOnWrite();
      instance.mergeCreatedAt(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp created_at = 1;</code>
     */
    public Builder clearCreatedAt() {  copyOnWrite();
      instance.clearCreatedAt();
      return this;
    }

    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    @java.lang.Override
    public boolean hasPresence() {
      return instance.hasPresence();
    }
    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.PresenceEvent getPresence() {
      return instance.getPresence();
    }
    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    public Builder setPresence(com.example.messenger.proto.PresenceEvent value) {
      copyOnWrite();
      instance.setPresence(value);
      return this;
    }
    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    public Builder setPresence(
        com.example.messenger.proto.PresenceEvent.Builder builderForValue) {
      copyOnWrite();
      instance.setPresence(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    public Builder mergePresence(com.example.messenger.proto.PresenceEvent value) {
      copyOnWrite();
      instance.mergePresence(value);
      return this;
    }
    /**
     * <code>.messenger.v1.PresenceEvent presence = 2;</code>
     */
    public Builder clearPresence() {
      copyOnWrite();
      instance.clearPresence();
      return this;
    }

    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    @java.lang.Override
    public boolean hasMessage() {
      return instance.hasMessage();
    }
    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.Message getMessage() {
      return instance.getMessage();
    }
    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    public Builder setMessage(com.example.messenger.proto.Message value) {
      copyOnWrite();
      instance.setMessage(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    public Builder setMessage(
        com.example.messenger.proto.Message.Builder builderForValue) {
      copyOnWrite();
      instance.setMessage(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    public Builder mergeMessage(com.example.messenger.proto.Message value) {
      copyOnWrite();
      instance.mergeMessage(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Message message = 3;</code>
     */
    public Builder clearMessage() {
      copyOnWrite();
      instance.clearMessage();
      return this;
    }

    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    @java.lang.Override
    public boolean hasProfile() {
      return instance.hasProfile();
    }
    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.ProfileEvent getProfile() {
      return instance.getProfile();
    }
    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    public Builder setProfile(com.example.messenger.proto.ProfileEvent value) {
      copyOnWrite();
      instance.setProfile(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    public Builder setProfile(
        com.example.messenger.proto.ProfileEvent.Builder builderForValue) {
      copyOnWrite();
      instance.setProfile(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    public Builder mergeProfile(com.example.messenger.proto.ProfileEvent value) {
      copyOnWrite();
      instance.mergeProfile(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ProfileEvent profile = 4;</code>
     */
    public Builder clearProfile() {
      copyOnWrite();
      instance.clearProfile();
      return this;
    }

    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    @java.lang.Override
    public boolean hasMessageDeleted() {
      return instance.hasMessageDeleted();
    }
    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.MessageDeletedEvent getMessageDeleted() {
      return instance.getMessageDeleted();
    }
    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    public Builder setMessageDeleted(com.example.messenger.proto.MessageDeletedEvent value) {
      copyOnWrite();
      instance.setMessageDeleted(value);
      return this;
    }
    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    public Builder setMessageDeleted(
        com.example.messenger.proto.MessageDeletedEvent.Builder builderForValue) {
      copyOnWrite();
      instance.setMessageDeleted(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    public Builder mergeMessageDeleted(com.example.messenger.proto.MessageDeletedEvent value) {
      copyOnWrite();
      instance.mergeMessageDeleted(value);
      return this;
    }
    /**
     * <code>.messenger.v1.MessageDeletedEvent message_deleted = 5;</code>
     */
    public Builder clearMessageDeleted() {
      copyOnWrite();
      instance.clearMessageDeleted();
      return this;
    }

    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    @java.lang.Override
    public boolean hasConversation() {
      return instance.hasConversation();
    }
    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.Conversation getConversation() {
      return instance.getConversation();
    }
    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    public Builder setConversation(com.example.messenger.proto.Conversation value) {
      copyOnWrite();
      instance.setConversation(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    public Builder setConversation(
        com.example.messenger.proto.Conversation.Builder builderForValue) {
      copyOnWrite();
      instance.setConversation(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    public Builder mergeConversation(com.example.messenger.proto.Conversation value) {
      copyOnWrite();
      instance.mergeConversation(value);
      return this;
    }
    /**
     * <code>.messenger.v1.Conversation conversation = 6;</code>
     */
    public Builder clearConversation() {
      copyOnWrite();
      instance.clearConversation();
      return this;
    }

    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    @java.lang.Override
    public boolean hasConversationRemoved() {
      return instance.hasConversationRemoved();
    }
    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    @java.lang.Override
    public com.example.messenger.proto.ConversationRemovedEvent getConversationRemoved() {
      return instance.getConversationRemoved();
    }
    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    public Builder setConversationRemoved(com.example.messenger.proto.ConversationRemovedEvent value) {
      copyOnWrite();
      instance.setConversationRemoved(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    public Builder setConversationRemoved(
        com.example.messenger.proto.ConversationRemovedEvent.Builder builderForValue) {
      copyOnWrite();
      instance.setConversationRemoved(builderForValue.build());
      return this;
    }
    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    public Builder mergeConversationRemoved(com.example.messenger.proto.ConversationRemovedEvent value) {
      copyOnWrite();
      instance.mergeConversationRemoved(value);
      return this;
    }
    /**
     * <code>.messenger.v1.ConversationRemovedEvent conversation_removed = 7;</code>
     */
    public Builder clearConversationRemoved() {
      copyOnWrite();
      instance.clearConversationRemoved();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:messenger.v1.ServerEvent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.messenger.proto.ServerEvent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "payload_",
            "payloadCase_",
            "bitField0_",
            "createdAt_",
            com.example.messenger.proto.PresenceEvent.class,
            com.example.messenger.proto.Message.class,
            com.example.messenger.proto.ProfileEvent.class,
            com.example.messenger.proto.MessageDeletedEvent.class,
            com.example.messenger.proto.Conversation.class,
            com.example.messenger.proto.ConversationRemovedEvent.class,
          };
          java.lang.String info =
              "\u0000\u0007\u0001\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u1009\u0000\u0002" +
              "<\u0000\u0003<\u0000\u0004<\u0000\u0005<\u0000\u0006<\u0000\u0007<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.messenger.proto.ServerEvent> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.messenger.proto.ServerEvent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.messenger.proto.ServerEvent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:messenger.v1.ServerEvent)
  private static final com.example.messenger.proto.ServerEvent DEFAULT_INSTANCE;
  static {
    ServerEvent defaultInstance = new ServerEvent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ServerEvent.class, defaultInstance);
  }

  public static com.example.messenger.proto.ServerEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ServerEvent> PARSER;

  public static com.google.protobuf.Parser<ServerEvent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

