// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializestreamEventsRequest")
public inline fun streamEventsRequest(block: com.example.messenger.proto.StreamEventsRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.StreamEventsRequest =
  com.example.messenger.proto.StreamEventsRequestKt.Dsl._create(com.example.messenger.proto.StreamEventsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.StreamEventsRequest`
 */
public object StreamEventsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.StreamEventsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.StreamEventsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.StreamEventsRequest = _builder.build()
  }
}
public inline fun com.example.messenger.proto.StreamEventsRequest.copy(block: `com.example.messenger.proto`.StreamEventsRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.StreamEventsRequest =
  `com.example.messenger.proto`.StreamEventsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

