// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.messenger.proto;

@kotlin.jvm.JvmName("-initializetransferGroupAdminRequest")
public inline fun transferGroupAdminRequest(block: com.example.messenger.proto.TransferGroupAdminRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.TransferGroupAdminRequest =
  com.example.messenger.proto.TransferGroupAdminRequestKt.Dsl._create(com.example.messenger.proto.TransferGroupAdminRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `messenger.v1.TransferGroupAdminRequest`
 */
public object TransferGroupAdminRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.messenger.proto.TransferGroupAdminRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.example.messenger.proto.TransferGroupAdminRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.example.messenger.proto.TransferGroupAdminRequest = _builder.build()

    /**
     * `string conversation_id = 1;`
     */
    public var conversationId: kotlin.String
      @kotlin.jvm.JvmName("getConversationId")
        get() = _builder.conversationId
      @kotlin.jvm.JvmName("setConversationId")
        set(value) {
        _builder.conversationId = value
      }
    /**
     * `string conversation_id = 1;`
     */
    public fun clearConversationId() {
      _builder.clearConversationId()
    }

    /**
     * `string username = 2;`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2;`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }
  }
}
public inline fun com.example.messenger.proto.TransferGroupAdminRequest.copy(block: `com.example.messenger.proto`.TransferGroupAdminRequestKt.Dsl.() -> kotlin.Unit): com.example.messenger.proto.TransferGroupAdminRequest =
  `com.example.messenger.proto`.TransferGroupAdminRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

