// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: messenger/v1/messenger.proto
// Protobuf Java Version: 4.29.3

package com.example.messenger.proto;

public interface UploadMediaResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:messenger.v1.UploadMediaResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string media_id = 1;</code>
   * @return The mediaId.
   */
  java.lang.String getMediaId();
  /**
   * <code>string media_id = 1;</code>
   * @return The bytes for mediaId.
   */
  com.google.protobuf.ByteString
      getMediaIdBytes();
}
